/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as RegisterSuccessRouteImport } from "./routes/register-success"
import { Route as RegisterConfirmRouteImport } from "./routes/register-confirm"
import { Route as RegisterRouteImport } from "./routes/register"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as AiAssistantRouteImport } from "./routes/ai-assistant"
import { Route as R403RouteImport } from "./routes/403"
import { Route as appRouteRouteImport } from "./routes/(app)/route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as PapersIndexRouteImport } from "./routes/papers/index"
import { Route as ConferencesIndexRouteImport } from "./routes/conferences/index"
import { Route as PapersPaperIdRouteImport } from "./routes/papers/$paperId"
import { Route as ConferencesConferenceIdRouteImport } from "./routes/conferences/$conferenceId"
import { Route as appTicketsRouteImport } from "./routes/(app)/tickets"
import { Route as appProfileRouteImport } from "./routes/(app)/profile"
import { Route as appProceedingsRouteImport } from "./routes/(app)/proceedings"
import { Route as appCheckinRouteImport } from "./routes/(app)/checkin"
import { Route as appAttendancesRouteImport } from "./routes/(app)/attendances"
import { Route as appSessionsAssignRouteImport } from "./routes/(app)/sessions.assign"
import { Route as appPapersSubmitRouteImport } from "./routes/(app)/papers.submit"
import { Route as appNotificationsCreateRouteImport } from "./routes/(app)/notifications.create"
import { Route as appConferencesCreateRouteImport } from "./routes/(app)/conferences.create"
import { Route as appAgendaMeRouteImport } from "./routes/(app)/agenda.me"
import { Route as appPapersMeIndexRouteImport } from "./routes/(app)/papers/me/index"
import { Route as appPapersMePaperIdRouteImport } from "./routes/(app)/papers/me/$paperId"

const RegisterSuccessRoute = RegisterSuccessRouteImport.update({
  id: "/register-success",
  path: "/register-success",
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterConfirmRoute = RegisterConfirmRouteImport.update({
  id: "/register-confirm",
  path: "/register-confirm",
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: "/ai-assistant",
  path: "/ai-assistant",
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: "/403",
  path: "/403",
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: "/(app)",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const PapersIndexRoute = PapersIndexRouteImport.update({
  id: "/papers/",
  path: "/papers/",
  getParentRoute: () => rootRouteImport,
} as any)
const ConferencesIndexRoute = ConferencesIndexRouteImport.update({
  id: "/conferences/",
  path: "/conferences/",
  getParentRoute: () => rootRouteImport,
} as any)
const PapersPaperIdRoute = PapersPaperIdRouteImport.update({
  id: "/papers/$paperId",
  path: "/papers/$paperId",
  getParentRoute: () => rootRouteImport,
} as any)
const ConferencesConferenceIdRoute = ConferencesConferenceIdRouteImport.update({
  id: "/conferences/$conferenceId",
  path: "/conferences/$conferenceId",
  getParentRoute: () => rootRouteImport,
} as any)
const appTicketsRoute = appTicketsRouteImport.update({
  id: "/tickets",
  path: "/tickets",
  getParentRoute: () => appRouteRoute,
} as any)
const appProfileRoute = appProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => appRouteRoute,
} as any)
const appProceedingsRoute = appProceedingsRouteImport.update({
  id: "/proceedings",
  path: "/proceedings",
  getParentRoute: () => appRouteRoute,
} as any)
const appCheckinRoute = appCheckinRouteImport.update({
  id: "/checkin",
  path: "/checkin",
  getParentRoute: () => appRouteRoute,
} as any)
const appAttendancesRoute = appAttendancesRouteImport.update({
  id: "/attendances",
  path: "/attendances",
  getParentRoute: () => appRouteRoute,
} as any)
const appSessionsAssignRoute = appSessionsAssignRouteImport.update({
  id: "/sessions/assign",
  path: "/sessions/assign",
  getParentRoute: () => appRouteRoute,
} as any)
const appPapersSubmitRoute = appPapersSubmitRouteImport.update({
  id: "/papers/submit",
  path: "/papers/submit",
  getParentRoute: () => appRouteRoute,
} as any)
const appNotificationsCreateRoute = appNotificationsCreateRouteImport.update({
  id: "/notifications/create",
  path: "/notifications/create",
  getParentRoute: () => appRouteRoute,
} as any)
const appConferencesCreateRoute = appConferencesCreateRouteImport.update({
  id: "/conferences/create",
  path: "/conferences/create",
  getParentRoute: () => appRouteRoute,
} as any)
const appAgendaMeRoute = appAgendaMeRouteImport.update({
  id: "/agenda/me",
  path: "/agenda/me",
  getParentRoute: () => appRouteRoute,
} as any)
const appPapersMeIndexRoute = appPapersMeIndexRouteImport.update({
  id: "/papers/me/",
  path: "/papers/me/",
  getParentRoute: () => appRouteRoute,
} as any)
const appPapersMePaperIdRoute = appPapersMePaperIdRouteImport.update({
  id: "/papers/me/$paperId",
  path: "/papers/me/$paperId",
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/403": typeof R403Route
  "/ai-assistant": typeof AiAssistantRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/register-confirm": typeof RegisterConfirmRoute
  "/register-success": typeof RegisterSuccessRoute
  "/attendances": typeof appAttendancesRoute
  "/checkin": typeof appCheckinRoute
  "/proceedings": typeof appProceedingsRoute
  "/profile": typeof appProfileRoute
  "/tickets": typeof appTicketsRoute
  "/conferences/$conferenceId": typeof ConferencesConferenceIdRoute
  "/papers/$paperId": typeof PapersPaperIdRoute
  "/conferences/": typeof ConferencesIndexRoute
  "/papers/": typeof PapersIndexRoute
  "/agenda/me": typeof appAgendaMeRoute
  "/conferences/create": typeof appConferencesCreateRoute
  "/notifications/create": typeof appNotificationsCreateRoute
  "/papers/submit": typeof appPapersSubmitRoute
  "/sessions/assign": typeof appSessionsAssignRoute
  "/papers/me/$paperId": typeof appPapersMePaperIdRoute
  "/papers/me/": typeof appPapersMeIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/403": typeof R403Route
  "/ai-assistant": typeof AiAssistantRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/register-confirm": typeof RegisterConfirmRoute
  "/register-success": typeof RegisterSuccessRoute
  "/attendances": typeof appAttendancesRoute
  "/checkin": typeof appCheckinRoute
  "/proceedings": typeof appProceedingsRoute
  "/profile": typeof appProfileRoute
  "/tickets": typeof appTicketsRoute
  "/conferences/$conferenceId": typeof ConferencesConferenceIdRoute
  "/papers/$paperId": typeof PapersPaperIdRoute
  "/conferences": typeof ConferencesIndexRoute
  "/papers": typeof PapersIndexRoute
  "/agenda/me": typeof appAgendaMeRoute
  "/conferences/create": typeof appConferencesCreateRoute
  "/notifications/create": typeof appNotificationsCreateRoute
  "/papers/submit": typeof appPapersSubmitRoute
  "/sessions/assign": typeof appSessionsAssignRoute
  "/papers/me/$paperId": typeof appPapersMePaperIdRoute
  "/papers/me": typeof appPapersMeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/(app)": typeof appRouteRouteWithChildren
  "/403": typeof R403Route
  "/ai-assistant": typeof AiAssistantRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/register-confirm": typeof RegisterConfirmRoute
  "/register-success": typeof RegisterSuccessRoute
  "/(app)/attendances": typeof appAttendancesRoute
  "/(app)/checkin": typeof appCheckinRoute
  "/(app)/proceedings": typeof appProceedingsRoute
  "/(app)/profile": typeof appProfileRoute
  "/(app)/tickets": typeof appTicketsRoute
  "/conferences/$conferenceId": typeof ConferencesConferenceIdRoute
  "/papers/$paperId": typeof PapersPaperIdRoute
  "/conferences/": typeof ConferencesIndexRoute
  "/papers/": typeof PapersIndexRoute
  "/(app)/agenda/me": typeof appAgendaMeRoute
  "/(app)/conferences/create": typeof appConferencesCreateRoute
  "/(app)/notifications/create": typeof appNotificationsCreateRoute
  "/(app)/papers/submit": typeof appPapersSubmitRoute
  "/(app)/sessions/assign": typeof appSessionsAssignRoute
  "/(app)/papers/me/$paperId": typeof appPapersMePaperIdRoute
  "/(app)/papers/me/": typeof appPapersMeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/403"
    | "/ai-assistant"
    | "/login"
    | "/register"
    | "/register-confirm"
    | "/register-success"
    | "/attendances"
    | "/checkin"
    | "/proceedings"
    | "/profile"
    | "/tickets"
    | "/conferences/$conferenceId"
    | "/papers/$paperId"
    | "/conferences/"
    | "/papers/"
    | "/agenda/me"
    | "/conferences/create"
    | "/notifications/create"
    | "/papers/submit"
    | "/sessions/assign"
    | "/papers/me/$paperId"
    | "/papers/me/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/403"
    | "/ai-assistant"
    | "/login"
    | "/register"
    | "/register-confirm"
    | "/register-success"
    | "/attendances"
    | "/checkin"
    | "/proceedings"
    | "/profile"
    | "/tickets"
    | "/conferences/$conferenceId"
    | "/papers/$paperId"
    | "/conferences"
    | "/papers"
    | "/agenda/me"
    | "/conferences/create"
    | "/notifications/create"
    | "/papers/submit"
    | "/sessions/assign"
    | "/papers/me/$paperId"
    | "/papers/me"
  id:
    | "__root__"
    | "/"
    | "/(app)"
    | "/403"
    | "/ai-assistant"
    | "/login"
    | "/register"
    | "/register-confirm"
    | "/register-success"
    | "/(app)/attendances"
    | "/(app)/checkin"
    | "/(app)/proceedings"
    | "/(app)/profile"
    | "/(app)/tickets"
    | "/conferences/$conferenceId"
    | "/papers/$paperId"
    | "/conferences/"
    | "/papers/"
    | "/(app)/agenda/me"
    | "/(app)/conferences/create"
    | "/(app)/notifications/create"
    | "/(app)/papers/submit"
    | "/(app)/sessions/assign"
    | "/(app)/papers/me/$paperId"
    | "/(app)/papers/me/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  R403Route: typeof R403Route
  AiAssistantRoute: typeof AiAssistantRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RegisterConfirmRoute: typeof RegisterConfirmRoute
  RegisterSuccessRoute: typeof RegisterSuccessRoute
  ConferencesConferenceIdRoute: typeof ConferencesConferenceIdRoute
  PapersPaperIdRoute: typeof PapersPaperIdRoute
  ConferencesIndexRoute: typeof ConferencesIndexRoute
  PapersIndexRoute: typeof PapersIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/register-success": {
      id: "/register-success"
      path: "/register-success"
      fullPath: "/register-success"
      preLoaderRoute: typeof RegisterSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/register-confirm": {
      id: "/register-confirm"
      path: "/register-confirm"
      fullPath: "/register-confirm"
      preLoaderRoute: typeof RegisterConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/ai-assistant": {
      id: "/ai-assistant"
      path: "/ai-assistant"
      fullPath: "/ai-assistant"
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/403": {
      id: "/403"
      path: "/403"
      fullPath: "/403"
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(app)": {
      id: "/(app)"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/papers/": {
      id: "/papers/"
      path: "/papers"
      fullPath: "/papers/"
      preLoaderRoute: typeof PapersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/conferences/": {
      id: "/conferences/"
      path: "/conferences"
      fullPath: "/conferences/"
      preLoaderRoute: typeof ConferencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/papers/$paperId": {
      id: "/papers/$paperId"
      path: "/papers/$paperId"
      fullPath: "/papers/$paperId"
      preLoaderRoute: typeof PapersPaperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/conferences/$conferenceId": {
      id: "/conferences/$conferenceId"
      path: "/conferences/$conferenceId"
      fullPath: "/conferences/$conferenceId"
      preLoaderRoute: typeof ConferencesConferenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(app)/tickets": {
      id: "/(app)/tickets"
      path: "/tickets"
      fullPath: "/tickets"
      preLoaderRoute: typeof appTicketsRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/profile": {
      id: "/(app)/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof appProfileRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/proceedings": {
      id: "/(app)/proceedings"
      path: "/proceedings"
      fullPath: "/proceedings"
      preLoaderRoute: typeof appProceedingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/checkin": {
      id: "/(app)/checkin"
      path: "/checkin"
      fullPath: "/checkin"
      preLoaderRoute: typeof appCheckinRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/attendances": {
      id: "/(app)/attendances"
      path: "/attendances"
      fullPath: "/attendances"
      preLoaderRoute: typeof appAttendancesRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/sessions/assign": {
      id: "/(app)/sessions/assign"
      path: "/sessions/assign"
      fullPath: "/sessions/assign"
      preLoaderRoute: typeof appSessionsAssignRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/papers/submit": {
      id: "/(app)/papers/submit"
      path: "/papers/submit"
      fullPath: "/papers/submit"
      preLoaderRoute: typeof appPapersSubmitRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/notifications/create": {
      id: "/(app)/notifications/create"
      path: "/notifications/create"
      fullPath: "/notifications/create"
      preLoaderRoute: typeof appNotificationsCreateRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/conferences/create": {
      id: "/(app)/conferences/create"
      path: "/conferences/create"
      fullPath: "/conferences/create"
      preLoaderRoute: typeof appConferencesCreateRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/agenda/me": {
      id: "/(app)/agenda/me"
      path: "/agenda/me"
      fullPath: "/agenda/me"
      preLoaderRoute: typeof appAgendaMeRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/papers/me/": {
      id: "/(app)/papers/me/"
      path: "/papers/me"
      fullPath: "/papers/me/"
      preLoaderRoute: typeof appPapersMeIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/papers/me/$paperId": {
      id: "/(app)/papers/me/$paperId"
      path: "/papers/me/$paperId"
      fullPath: "/papers/me/$paperId"
      preLoaderRoute: typeof appPapersMePaperIdRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appAttendancesRoute: typeof appAttendancesRoute
  appCheckinRoute: typeof appCheckinRoute
  appProceedingsRoute: typeof appProceedingsRoute
  appProfileRoute: typeof appProfileRoute
  appTicketsRoute: typeof appTicketsRoute
  appAgendaMeRoute: typeof appAgendaMeRoute
  appConferencesCreateRoute: typeof appConferencesCreateRoute
  appNotificationsCreateRoute: typeof appNotificationsCreateRoute
  appPapersSubmitRoute: typeof appPapersSubmitRoute
  appSessionsAssignRoute: typeof appSessionsAssignRoute
  appPapersMePaperIdRoute: typeof appPapersMePaperIdRoute
  appPapersMeIndexRoute: typeof appPapersMeIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAttendancesRoute: appAttendancesRoute,
  appCheckinRoute: appCheckinRoute,
  appProceedingsRoute: appProceedingsRoute,
  appProfileRoute: appProfileRoute,
  appTicketsRoute: appTicketsRoute,
  appAgendaMeRoute: appAgendaMeRoute,
  appConferencesCreateRoute: appConferencesCreateRoute,
  appNotificationsCreateRoute: appNotificationsCreateRoute,
  appPapersSubmitRoute: appPapersSubmitRoute,
  appSessionsAssignRoute: appSessionsAssignRoute,
  appPapersMePaperIdRoute: appPapersMePaperIdRoute,
  appPapersMeIndexRoute: appPapersMeIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  R403Route: R403Route,
  AiAssistantRoute: AiAssistantRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RegisterConfirmRoute: RegisterConfirmRoute,
  RegisterSuccessRoute: RegisterSuccessRoute,
  ConferencesConferenceIdRoute: ConferencesConferenceIdRoute,
  PapersPaperIdRoute: PapersPaperIdRoute,
  ConferencesIndexRoute: ConferencesIndexRoute,
  PapersIndexRoute: PapersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
