/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SubscriptionsRouteImport } from "./routes/subscriptions"
import { Route as RegisterSuccessRouteImport } from "./routes/register-success"
import { Route as RegisterConfirmRouteImport } from "./routes/register-confirm"
import { Route as RegisterRouteImport } from "./routes/register"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as AiAssistantRouteImport } from "./routes/ai-assistant"
import { Route as R403RouteImport } from "./routes/403"
import { Route as appRouteRouteImport } from "./routes/(app)/route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as PapersIndexRouteImport } from "./routes/papers/index"
import { Route as ConferencesIndexRouteImport } from "./routes/conferences/index"
import { Route as PapersPaperIdRouteImport } from "./routes/papers/$paperId"
import { Route as ConferencesConferenceIdRouteImport } from "./routes/conferences/$conferenceId"
import { Route as appTicketsRouteImport } from "./routes/(app)/tickets"
import { Route as appProfileRouteImport } from "./routes/(app)/profile"
import { Route as appProceedingsRouteImport } from "./routes/(app)/proceedings"
import { Route as appCheckinRouteImport } from "./routes/(app)/checkin"
import { Route as appAttendancesRouteImport } from "./routes/(app)/attendances"
import { Route as appSessionsRouteRouteImport } from "./routes/(app)/sessions/route"
import { Route as appSessionsIndexRouteImport } from "./routes/(app)/sessions/index"
import { Route as appChairInvitationsIndexRouteImport } from "./routes/(app)/chair-invitations.index"
import { Route as appSubscriptionsMeRouteImport } from "./routes/(app)/subscriptions.me"
import { Route as appSessionsChairInvitationsRouteImport } from "./routes/(app)/sessions/chair-invitations"
import { Route as appSessionsAssignRouteImport } from "./routes/(app)/sessions.assign"
import { Route as appPapersSubmitRouteImport } from "./routes/(app)/papers.submit"
import { Route as appNotificationsCreateRouteImport } from "./routes/(app)/notifications.create"
import { Route as appConferencesCreateRouteImport } from "./routes/(app)/conferences.create"
import { Route as appChairInvitationsTokenRouteImport } from "./routes/(app)/chair-invitations.$token"
import { Route as appAgendaMeRouteImport } from "./routes/(app)/agenda.me"
import { Route as appPapersMeIndexRouteImport } from "./routes/(app)/papers/me/index"
import { Route as appPapersMePaperIdRouteImport } from "./routes/(app)/papers/me/$paperId"
import { Route as appConferencesConferenceIdImportPapersRouteImport } from "./routes/(app)/conferences.$conferenceId/import-papers"
import { Route as appConferencesConferenceIdSessionsRouteRouteImport } from "./routes/(app)/conferences.$conferenceId.sessions/route"
import { Route as appConferencesConferenceIdSessionsIndexRouteImport } from "./routes/(app)/conferences.$conferenceId.sessions/index"
import { Route as ConferencesConferenceIdPapersPaperIdQaRouteImport } from "./routes/conferences_.$conferenceId.papers.$paperId.qa"
import { Route as appConferencesConferenceIdSessionsSessionIdIndexRouteImport } from "./routes/(app)/conferences.$conferenceId.sessions/$sessionId/index"
import { Route as appConferencesConferenceIdSessionsSessionIdChairsRouteImport } from "./routes/(app)/conferences.$conferenceId.sessions/$sessionId/chairs"

const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: "/subscriptions",
  path: "/subscriptions",
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterSuccessRoute = RegisterSuccessRouteImport.update({
  id: "/register-success",
  path: "/register-success",
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterConfirmRoute = RegisterConfirmRouteImport.update({
  id: "/register-confirm",
  path: "/register-confirm",
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: "/ai-assistant",
  path: "/ai-assistant",
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: "/403",
  path: "/403",
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: "/(app)",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const PapersIndexRoute = PapersIndexRouteImport.update({
  id: "/papers/",
  path: "/papers/",
  getParentRoute: () => rootRouteImport,
} as any)
const ConferencesIndexRoute = ConferencesIndexRouteImport.update({
  id: "/conferences/",
  path: "/conferences/",
  getParentRoute: () => rootRouteImport,
} as any)
const PapersPaperIdRoute = PapersPaperIdRouteImport.update({
  id: "/papers/$paperId",
  path: "/papers/$paperId",
  getParentRoute: () => rootRouteImport,
} as any)
const ConferencesConferenceIdRoute = ConferencesConferenceIdRouteImport.update({
  id: "/conferences/$conferenceId",
  path: "/conferences/$conferenceId",
  getParentRoute: () => rootRouteImport,
} as any)
const appTicketsRoute = appTicketsRouteImport.update({
  id: "/tickets",
  path: "/tickets",
  getParentRoute: () => appRouteRoute,
} as any)
const appProfileRoute = appProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => appRouteRoute,
} as any)
const appProceedingsRoute = appProceedingsRouteImport.update({
  id: "/proceedings",
  path: "/proceedings",
  getParentRoute: () => appRouteRoute,
} as any)
const appCheckinRoute = appCheckinRouteImport.update({
  id: "/checkin",
  path: "/checkin",
  getParentRoute: () => appRouteRoute,
} as any)
const appAttendancesRoute = appAttendancesRouteImport.update({
  id: "/attendances",
  path: "/attendances",
  getParentRoute: () => appRouteRoute,
} as any)
const appSessionsRouteRoute = appSessionsRouteRouteImport.update({
  id: "/sessions",
  path: "/sessions",
  getParentRoute: () => appRouteRoute,
} as any)
const appSessionsIndexRoute = appSessionsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => appSessionsRouteRoute,
} as any)
const appChairInvitationsIndexRoute =
  appChairInvitationsIndexRouteImport.update({
    id: "/chair-invitations/",
    path: "/chair-invitations/",
    getParentRoute: () => appRouteRoute,
  } as any)
const appSubscriptionsMeRoute = appSubscriptionsMeRouteImport.update({
  id: "/subscriptions/me",
  path: "/subscriptions/me",
  getParentRoute: () => appRouteRoute,
} as any)
const appSessionsChairInvitationsRoute =
  appSessionsChairInvitationsRouteImport.update({
    id: "/chair-invitations",
    path: "/chair-invitations",
    getParentRoute: () => appSessionsRouteRoute,
  } as any)
const appSessionsAssignRoute = appSessionsAssignRouteImport.update({
  id: "/assign",
  path: "/assign",
  getParentRoute: () => appSessionsRouteRoute,
} as any)
const appPapersSubmitRoute = appPapersSubmitRouteImport.update({
  id: "/papers/submit",
  path: "/papers/submit",
  getParentRoute: () => appRouteRoute,
} as any)
const appNotificationsCreateRoute = appNotificationsCreateRouteImport.update({
  id: "/notifications/create",
  path: "/notifications/create",
  getParentRoute: () => appRouteRoute,
} as any)
const appConferencesCreateRoute = appConferencesCreateRouteImport.update({
  id: "/conferences/create",
  path: "/conferences/create",
  getParentRoute: () => appRouteRoute,
} as any)
const appChairInvitationsTokenRoute =
  appChairInvitationsTokenRouteImport.update({
    id: "/chair-invitations/$token",
    path: "/chair-invitations/$token",
    getParentRoute: () => appRouteRoute,
  } as any)
const appAgendaMeRoute = appAgendaMeRouteImport.update({
  id: "/agenda/me",
  path: "/agenda/me",
  getParentRoute: () => appRouteRoute,
} as any)
const appPapersMeIndexRoute = appPapersMeIndexRouteImport.update({
  id: "/papers/me/",
  path: "/papers/me/",
  getParentRoute: () => appRouteRoute,
} as any)
const appPapersMePaperIdRoute = appPapersMePaperIdRouteImport.update({
  id: "/papers/me/$paperId",
  path: "/papers/me/$paperId",
  getParentRoute: () => appRouteRoute,
} as any)
const appConferencesConferenceIdImportPapersRoute =
  appConferencesConferenceIdImportPapersRouteImport.update({
    id: "/conferences/$conferenceId/import-papers",
    path: "/conferences/$conferenceId/import-papers",
    getParentRoute: () => appRouteRoute,
  } as any)
const appConferencesConferenceIdSessionsRouteRoute =
  appConferencesConferenceIdSessionsRouteRouteImport.update({
    id: "/conferences/$conferenceId/sessions",
    path: "/conferences/$conferenceId/sessions",
    getParentRoute: () => appRouteRoute,
  } as any)
const appConferencesConferenceIdSessionsIndexRoute =
  appConferencesConferenceIdSessionsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => appConferencesConferenceIdSessionsRouteRoute,
  } as any)
const ConferencesConferenceIdPapersPaperIdQaRoute =
  ConferencesConferenceIdPapersPaperIdQaRouteImport.update({
    id: "/conferences_/$conferenceId/papers/$paperId/qa",
    path: "/conferences/$conferenceId/papers/$paperId/qa",
    getParentRoute: () => rootRouteImport,
  } as any)
const appConferencesConferenceIdSessionsSessionIdIndexRoute =
  appConferencesConferenceIdSessionsSessionIdIndexRouteImport.update({
    id: "/$sessionId/",
    path: "/$sessionId/",
    getParentRoute: () => appConferencesConferenceIdSessionsRouteRoute,
  } as any)
const appConferencesConferenceIdSessionsSessionIdChairsRoute =
  appConferencesConferenceIdSessionsSessionIdChairsRouteImport.update({
    id: "/$sessionId/chairs",
    path: "/$sessionId/chairs",
    getParentRoute: () => appConferencesConferenceIdSessionsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/403": typeof R403Route
  "/ai-assistant": typeof AiAssistantRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/register-confirm": typeof RegisterConfirmRoute
  "/register-success": typeof RegisterSuccessRoute
  "/subscriptions": typeof SubscriptionsRoute
  "/sessions": typeof appSessionsRouteRouteWithChildren
  "/attendances": typeof appAttendancesRoute
  "/checkin": typeof appCheckinRoute
  "/proceedings": typeof appProceedingsRoute
  "/profile": typeof appProfileRoute
  "/tickets": typeof appTicketsRoute
  "/conferences/$conferenceId": typeof ConferencesConferenceIdRoute
  "/papers/$paperId": typeof PapersPaperIdRoute
  "/conferences/": typeof ConferencesIndexRoute
  "/papers/": typeof PapersIndexRoute
  "/agenda/me": typeof appAgendaMeRoute
  "/chair-invitations/$token": typeof appChairInvitationsTokenRoute
  "/conferences/create": typeof appConferencesCreateRoute
  "/notifications/create": typeof appNotificationsCreateRoute
  "/papers/submit": typeof appPapersSubmitRoute
  "/sessions/assign": typeof appSessionsAssignRoute
  "/sessions/chair-invitations": typeof appSessionsChairInvitationsRoute
  "/subscriptions/me": typeof appSubscriptionsMeRoute
  "/chair-invitations/": typeof appChairInvitationsIndexRoute
  "/sessions/": typeof appSessionsIndexRoute
  "/conferences/$conferenceId/sessions": typeof appConferencesConferenceIdSessionsRouteRouteWithChildren
  "/conferences/$conferenceId/import-papers": typeof appConferencesConferenceIdImportPapersRoute
  "/papers/me/$paperId": typeof appPapersMePaperIdRoute
  "/papers/me/": typeof appPapersMeIndexRoute
  "/conferences/$conferenceId/papers/$paperId/qa": typeof ConferencesConferenceIdPapersPaperIdQaRoute
  "/conferences/$conferenceId/sessions/": typeof appConferencesConferenceIdSessionsIndexRoute
  "/conferences/$conferenceId/sessions/$sessionId/chairs": typeof appConferencesConferenceIdSessionsSessionIdChairsRoute
  "/conferences/$conferenceId/sessions/$sessionId/": typeof appConferencesConferenceIdSessionsSessionIdIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/403": typeof R403Route
  "/ai-assistant": typeof AiAssistantRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/register-confirm": typeof RegisterConfirmRoute
  "/register-success": typeof RegisterSuccessRoute
  "/subscriptions": typeof SubscriptionsRoute
  "/attendances": typeof appAttendancesRoute
  "/checkin": typeof appCheckinRoute
  "/proceedings": typeof appProceedingsRoute
  "/profile": typeof appProfileRoute
  "/tickets": typeof appTicketsRoute
  "/conferences/$conferenceId": typeof ConferencesConferenceIdRoute
  "/papers/$paperId": typeof PapersPaperIdRoute
  "/conferences": typeof ConferencesIndexRoute
  "/papers": typeof PapersIndexRoute
  "/agenda/me": typeof appAgendaMeRoute
  "/chair-invitations/$token": typeof appChairInvitationsTokenRoute
  "/conferences/create": typeof appConferencesCreateRoute
  "/notifications/create": typeof appNotificationsCreateRoute
  "/papers/submit": typeof appPapersSubmitRoute
  "/sessions/assign": typeof appSessionsAssignRoute
  "/sessions/chair-invitations": typeof appSessionsChairInvitationsRoute
  "/subscriptions/me": typeof appSubscriptionsMeRoute
  "/chair-invitations": typeof appChairInvitationsIndexRoute
  "/sessions": typeof appSessionsIndexRoute
  "/conferences/$conferenceId/import-papers": typeof appConferencesConferenceIdImportPapersRoute
  "/papers/me/$paperId": typeof appPapersMePaperIdRoute
  "/papers/me": typeof appPapersMeIndexRoute
  "/conferences/$conferenceId/papers/$paperId/qa": typeof ConferencesConferenceIdPapersPaperIdQaRoute
  "/conferences/$conferenceId/sessions": typeof appConferencesConferenceIdSessionsIndexRoute
  "/conferences/$conferenceId/sessions/$sessionId/chairs": typeof appConferencesConferenceIdSessionsSessionIdChairsRoute
  "/conferences/$conferenceId/sessions/$sessionId": typeof appConferencesConferenceIdSessionsSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/(app)": typeof appRouteRouteWithChildren
  "/403": typeof R403Route
  "/ai-assistant": typeof AiAssistantRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/register-confirm": typeof RegisterConfirmRoute
  "/register-success": typeof RegisterSuccessRoute
  "/subscriptions": typeof SubscriptionsRoute
  "/(app)/sessions": typeof appSessionsRouteRouteWithChildren
  "/(app)/attendances": typeof appAttendancesRoute
  "/(app)/checkin": typeof appCheckinRoute
  "/(app)/proceedings": typeof appProceedingsRoute
  "/(app)/profile": typeof appProfileRoute
  "/(app)/tickets": typeof appTicketsRoute
  "/conferences/$conferenceId": typeof ConferencesConferenceIdRoute
  "/papers/$paperId": typeof PapersPaperIdRoute
  "/conferences/": typeof ConferencesIndexRoute
  "/papers/": typeof PapersIndexRoute
  "/(app)/agenda/me": typeof appAgendaMeRoute
  "/(app)/chair-invitations/$token": typeof appChairInvitationsTokenRoute
  "/(app)/conferences/create": typeof appConferencesCreateRoute
  "/(app)/notifications/create": typeof appNotificationsCreateRoute
  "/(app)/papers/submit": typeof appPapersSubmitRoute
  "/(app)/sessions/assign": typeof appSessionsAssignRoute
  "/(app)/sessions/chair-invitations": typeof appSessionsChairInvitationsRoute
  "/(app)/subscriptions/me": typeof appSubscriptionsMeRoute
  "/(app)/chair-invitations/": typeof appChairInvitationsIndexRoute
  "/(app)/sessions/": typeof appSessionsIndexRoute
  "/(app)/conferences/$conferenceId/sessions": typeof appConferencesConferenceIdSessionsRouteRouteWithChildren
  "/(app)/conferences/$conferenceId/import-papers": typeof appConferencesConferenceIdImportPapersRoute
  "/(app)/papers/me/$paperId": typeof appPapersMePaperIdRoute
  "/(app)/papers/me/": typeof appPapersMeIndexRoute
  "/conferences_/$conferenceId/papers/$paperId/qa": typeof ConferencesConferenceIdPapersPaperIdQaRoute
  "/(app)/conferences/$conferenceId/sessions/": typeof appConferencesConferenceIdSessionsIndexRoute
  "/(app)/conferences/$conferenceId/sessions/$sessionId/chairs": typeof appConferencesConferenceIdSessionsSessionIdChairsRoute
  "/(app)/conferences/$conferenceId/sessions/$sessionId/": typeof appConferencesConferenceIdSessionsSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
  | "/"
  | "/403"
  | "/ai-assistant"
  | "/login"
  | "/register"
  | "/register-confirm"
  | "/register-success"
  | "/subscriptions"
  | "/sessions"
  | "/attendances"
  | "/checkin"
  | "/proceedings"
  | "/profile"
  | "/tickets"
  | "/conferences/$conferenceId"
  | "/papers/$paperId"
  | "/conferences/"
  | "/papers/"
  | "/agenda/me"
  | "/chair-invitations/$token"
  | "/conferences/create"
  | "/notifications/create"
  | "/papers/submit"
  | "/sessions/assign"
  | "/sessions/chair-invitations"
  | "/subscriptions/me"
  | "/chair-invitations/"
  | "/sessions/"
  | "/conferences/$conferenceId/sessions"
  | "/conferences/$conferenceId/import-papers"
  | "/papers/me/$paperId"
  | "/papers/me/"
  | "/conferences/$conferenceId/papers/$paperId/qa"
  | "/conferences/$conferenceId/sessions/"
  | "/conferences/$conferenceId/sessions/$sessionId/chairs"
  | "/conferences/$conferenceId/sessions/$sessionId/"
  fileRoutesByTo: FileRoutesByTo
  to:
  | "/"
  | "/403"
  | "/ai-assistant"
  | "/login"
  | "/register"
  | "/register-confirm"
  | "/register-success"
  | "/subscriptions"
  | "/attendances"
  | "/checkin"
  | "/proceedings"
  | "/profile"
  | "/tickets"
  | "/conferences/$conferenceId"
  | "/papers/$paperId"
  | "/conferences"
  | "/papers"
  | "/agenda/me"
  | "/chair-invitations/$token"
  | "/conferences/create"
  | "/notifications/create"
  | "/papers/submit"
  | "/sessions/assign"
  | "/sessions/chair-invitations"
  | "/subscriptions/me"
  | "/chair-invitations"
  | "/sessions"
  | "/conferences/$conferenceId/import-papers"
  | "/papers/me/$paperId"
  | "/papers/me"
  | "/conferences/$conferenceId/papers/$paperId/qa"
  | "/conferences/$conferenceId/sessions"
  | "/conferences/$conferenceId/sessions/$sessionId/chairs"
  | "/conferences/$conferenceId/sessions/$sessionId"
  id:
  | "__root__"
  | "/"
  | "/(app)"
  | "/403"
  | "/ai-assistant"
  | "/login"
  | "/register"
  | "/register-confirm"
  | "/register-success"
  | "/subscriptions"
  | "/(app)/sessions"
  | "/(app)/attendances"
  | "/(app)/checkin"
  | "/(app)/proceedings"
  | "/(app)/profile"
  | "/(app)/tickets"
  | "/conferences/$conferenceId"
  | "/papers/$paperId"
  | "/conferences/"
  | "/papers/"
  | "/(app)/agenda/me"
  | "/(app)/chair-invitations/$token"
  | "/(app)/conferences/create"
  | "/(app)/notifications/create"
  | "/(app)/papers/submit"
  | "/(app)/sessions/assign"
  | "/(app)/sessions/chair-invitations"
  | "/(app)/subscriptions/me"
  | "/(app)/chair-invitations/"
  | "/(app)/sessions/"
  | "/(app)/conferences/$conferenceId/sessions"
  | "/(app)/conferences/$conferenceId/import-papers"
  | "/(app)/papers/me/$paperId"
  | "/(app)/papers/me/"
  | "/conferences_/$conferenceId/papers/$paperId/qa"
  | "/(app)/conferences/$conferenceId/sessions/"
  | "/(app)/conferences/$conferenceId/sessions/$sessionId/chairs"
  | "/(app)/conferences/$conferenceId/sessions/$sessionId/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  R403Route: typeof R403Route
  AiAssistantRoute: typeof AiAssistantRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RegisterConfirmRoute: typeof RegisterConfirmRoute
  RegisterSuccessRoute: typeof RegisterSuccessRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  ConferencesConferenceIdRoute: typeof ConferencesConferenceIdRoute
  PapersPaperIdRoute: typeof PapersPaperIdRoute
  ConferencesIndexRoute: typeof ConferencesIndexRoute
  PapersIndexRoute: typeof PapersIndexRoute
  ConferencesConferenceIdPapersPaperIdQaRoute: typeof ConferencesConferenceIdPapersPaperIdQaRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/subscriptions": {
      id: "/subscriptions"
      path: "/subscriptions"
      fullPath: "/subscriptions"
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/register-success": {
      id: "/register-success"
      path: "/register-success"
      fullPath: "/register-success"
      preLoaderRoute: typeof RegisterSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/register-confirm": {
      id: "/register-confirm"
      path: "/register-confirm"
      fullPath: "/register-confirm"
      preLoaderRoute: typeof RegisterConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/ai-assistant": {
      id: "/ai-assistant"
      path: "/ai-assistant"
      fullPath: "/ai-assistant"
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/403": {
      id: "/403"
      path: "/403"
      fullPath: "/403"
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(app)": {
      id: "/(app)"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/papers/": {
      id: "/papers/"
      path: "/papers"
      fullPath: "/papers/"
      preLoaderRoute: typeof PapersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/conferences/": {
      id: "/conferences/"
      path: "/conferences"
      fullPath: "/conferences/"
      preLoaderRoute: typeof ConferencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/papers/$paperId": {
      id: "/papers/$paperId"
      path: "/papers/$paperId"
      fullPath: "/papers/$paperId"
      preLoaderRoute: typeof PapersPaperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/conferences/$conferenceId": {
      id: "/conferences/$conferenceId"
      path: "/conferences/$conferenceId"
      fullPath: "/conferences/$conferenceId"
      preLoaderRoute: typeof ConferencesConferenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(app)/tickets": {
      id: "/(app)/tickets"
      path: "/tickets"
      fullPath: "/tickets"
      preLoaderRoute: typeof appTicketsRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/profile": {
      id: "/(app)/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof appProfileRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/proceedings": {
      id: "/(app)/proceedings"
      path: "/proceedings"
      fullPath: "/proceedings"
      preLoaderRoute: typeof appProceedingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/checkin": {
      id: "/(app)/checkin"
      path: "/checkin"
      fullPath: "/checkin"
      preLoaderRoute: typeof appCheckinRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/attendances": {
      id: "/(app)/attendances"
      path: "/attendances"
      fullPath: "/attendances"
      preLoaderRoute: typeof appAttendancesRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/sessions": {
      id: "/(app)/sessions"
      path: "/sessions"
      fullPath: "/sessions"
      preLoaderRoute: typeof appSessionsRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/sessions/": {
      id: "/(app)/sessions/"
      path: "/"
      fullPath: "/sessions/"
      preLoaderRoute: typeof appSessionsIndexRouteImport
      parentRoute: typeof appSessionsRouteRoute
    }
    "/(app)/chair-invitations/": {
      id: "/(app)/chair-invitations/"
      path: "/chair-invitations"
      fullPath: "/chair-invitations/"
      preLoaderRoute: typeof appChairInvitationsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/subscriptions/me": {
      id: "/(app)/subscriptions/me"
      path: "/subscriptions/me"
      fullPath: "/subscriptions/me"
      preLoaderRoute: typeof appSubscriptionsMeRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/sessions/chair-invitations": {
      id: "/(app)/sessions/chair-invitations"
      path: "/chair-invitations"
      fullPath: "/sessions/chair-invitations"
      preLoaderRoute: typeof appSessionsChairInvitationsRouteImport
      parentRoute: typeof appSessionsRouteRoute
    }
    "/(app)/sessions/assign": {
      id: "/(app)/sessions/assign"
      path: "/assign"
      fullPath: "/sessions/assign"
      preLoaderRoute: typeof appSessionsAssignRouteImport
      parentRoute: typeof appSessionsRouteRoute
    }
    "/(app)/papers/submit": {
      id: "/(app)/papers/submit"
      path: "/papers/submit"
      fullPath: "/papers/submit"
      preLoaderRoute: typeof appPapersSubmitRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/notifications/create": {
      id: "/(app)/notifications/create"
      path: "/notifications/create"
      fullPath: "/notifications/create"
      preLoaderRoute: typeof appNotificationsCreateRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/conferences/create": {
      id: "/(app)/conferences/create"
      path: "/conferences/create"
      fullPath: "/conferences/create"
      preLoaderRoute: typeof appConferencesCreateRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/chair-invitations/$token": {
      id: "/(app)/chair-invitations/$token"
      path: "/chair-invitations/$token"
      fullPath: "/chair-invitations/$token"
      preLoaderRoute: typeof appChairInvitationsTokenRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/agenda/me": {
      id: "/(app)/agenda/me"
      path: "/agenda/me"
      fullPath: "/agenda/me"
      preLoaderRoute: typeof appAgendaMeRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/papers/me/": {
      id: "/(app)/papers/me/"
      path: "/papers/me"
      fullPath: "/papers/me/"
      preLoaderRoute: typeof appPapersMeIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/papers/me/$paperId": {
      id: "/(app)/papers/me/$paperId"
      path: "/papers/me/$paperId"
      fullPath: "/papers/me/$paperId"
      preLoaderRoute: typeof appPapersMePaperIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/conferences/$conferenceId/import-papers": {
      id: "/(app)/conferences/$conferenceId/import-papers"
      path: "/conferences/$conferenceId/import-papers"
      fullPath: "/conferences/$conferenceId/import-papers"
      preLoaderRoute: typeof appConferencesConferenceIdImportPapersRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/conferences/$conferenceId/sessions": {
      id: "/(app)/conferences/$conferenceId/sessions"
      path: "/conferences/$conferenceId/sessions"
      fullPath: "/conferences/$conferenceId/sessions"
      preLoaderRoute: typeof appConferencesConferenceIdSessionsRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    "/(app)/conferences/$conferenceId/sessions/": {
      id: "/(app)/conferences/$conferenceId/sessions/"
      path: "/"
      fullPath: "/conferences/$conferenceId/sessions/"
      preLoaderRoute: typeof appConferencesConferenceIdSessionsIndexRouteImport
      parentRoute: typeof appConferencesConferenceIdSessionsRouteRoute
    }
    "/conferences_/$conferenceId/papers/$paperId/qa": {
      id: "/conferences_/$conferenceId/papers/$paperId/qa"
      path: "/conferences/$conferenceId/papers/$paperId/qa"
      fullPath: "/conferences/$conferenceId/papers/$paperId/qa"
      preLoaderRoute: typeof ConferencesConferenceIdPapersPaperIdQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(app)/conferences/$conferenceId/sessions/$sessionId/": {
      id: "/(app)/conferences/$conferenceId/sessions/$sessionId/"
      path: "/$sessionId"
      fullPath: "/conferences/$conferenceId/sessions/$sessionId/"
      preLoaderRoute: typeof appConferencesConferenceIdSessionsSessionIdIndexRouteImport
      parentRoute: typeof appConferencesConferenceIdSessionsRouteRoute
    }
    "/(app)/conferences/$conferenceId/sessions/$sessionId/chairs": {
      id: "/(app)/conferences/$conferenceId/sessions/$sessionId/chairs"
      path: "/$sessionId/chairs"
      fullPath: "/conferences/$conferenceId/sessions/$sessionId/chairs"
      preLoaderRoute: typeof appConferencesConferenceIdSessionsSessionIdChairsRouteImport
      parentRoute: typeof appConferencesConferenceIdSessionsRouteRoute
    }
  }
}

interface appSessionsRouteRouteChildren {
  appSessionsAssignRoute: typeof appSessionsAssignRoute
  appSessionsChairInvitationsRoute: typeof appSessionsChairInvitationsRoute
  appSessionsIndexRoute: typeof appSessionsIndexRoute
}

const appSessionsRouteRouteChildren: appSessionsRouteRouteChildren = {
  appSessionsAssignRoute: appSessionsAssignRoute,
  appSessionsChairInvitationsRoute: appSessionsChairInvitationsRoute,
  appSessionsIndexRoute: appSessionsIndexRoute,
}

const appSessionsRouteRouteWithChildren =
  appSessionsRouteRoute._addFileChildren(appSessionsRouteRouteChildren)

interface appConferencesConferenceIdSessionsRouteRouteChildren {
  appConferencesConferenceIdSessionsIndexRoute: typeof appConferencesConferenceIdSessionsIndexRoute
  appConferencesConferenceIdSessionsSessionIdChairsRoute: typeof appConferencesConferenceIdSessionsSessionIdChairsRoute
  appConferencesConferenceIdSessionsSessionIdIndexRoute: typeof appConferencesConferenceIdSessionsSessionIdIndexRoute
}

const appConferencesConferenceIdSessionsRouteRouteChildren: appConferencesConferenceIdSessionsRouteRouteChildren =
{
  appConferencesConferenceIdSessionsIndexRoute:
    appConferencesConferenceIdSessionsIndexRoute,
  appConferencesConferenceIdSessionsSessionIdChairsRoute:
    appConferencesConferenceIdSessionsSessionIdChairsRoute,
  appConferencesConferenceIdSessionsSessionIdIndexRoute:
    appConferencesConferenceIdSessionsSessionIdIndexRoute,
}

const appConferencesConferenceIdSessionsRouteRouteWithChildren =
  appConferencesConferenceIdSessionsRouteRoute._addFileChildren(
    appConferencesConferenceIdSessionsRouteRouteChildren,
  )

interface appRouteRouteChildren {
  appSessionsRouteRoute: typeof appSessionsRouteRouteWithChildren
  appAttendancesRoute: typeof appAttendancesRoute
  appCheckinRoute: typeof appCheckinRoute
  appProceedingsRoute: typeof appProceedingsRoute
  appProfileRoute: typeof appProfileRoute
  appTicketsRoute: typeof appTicketsRoute
  appAgendaMeRoute: typeof appAgendaMeRoute
  appChairInvitationsTokenRoute: typeof appChairInvitationsTokenRoute
  appConferencesCreateRoute: typeof appConferencesCreateRoute
  appNotificationsCreateRoute: typeof appNotificationsCreateRoute
  appPapersSubmitRoute: typeof appPapersSubmitRoute
  appSubscriptionsMeRoute: typeof appSubscriptionsMeRoute
  appChairInvitationsIndexRoute: typeof appChairInvitationsIndexRoute
  appConferencesConferenceIdSessionsRouteRoute: typeof appConferencesConferenceIdSessionsRouteRouteWithChildren
  appConferencesConferenceIdImportPapersRoute: typeof appConferencesConferenceIdImportPapersRoute
  appPapersMePaperIdRoute: typeof appPapersMePaperIdRoute
  appPapersMeIndexRoute: typeof appPapersMeIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appSessionsRouteRoute: appSessionsRouteRouteWithChildren,
  appAttendancesRoute: appAttendancesRoute,
  appCheckinRoute: appCheckinRoute,
  appProceedingsRoute: appProceedingsRoute,
  appProfileRoute: appProfileRoute,
  appTicketsRoute: appTicketsRoute,
  appAgendaMeRoute: appAgendaMeRoute,
  appChairInvitationsTokenRoute: appChairInvitationsTokenRoute,
  appConferencesCreateRoute: appConferencesCreateRoute,
  appNotificationsCreateRoute: appNotificationsCreateRoute,
  appPapersSubmitRoute: appPapersSubmitRoute,
  appSubscriptionsMeRoute: appSubscriptionsMeRoute,
  appChairInvitationsIndexRoute: appChairInvitationsIndexRoute,
  appConferencesConferenceIdSessionsRouteRoute:
    appConferencesConferenceIdSessionsRouteRouteWithChildren,
  appConferencesConferenceIdImportPapersRoute:
    appConferencesConferenceIdImportPapersRoute,
  appPapersMePaperIdRoute: appPapersMePaperIdRoute,
  appPapersMeIndexRoute: appPapersMeIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  R403Route: R403Route,
  AiAssistantRoute: AiAssistantRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RegisterConfirmRoute: RegisterConfirmRoute,
  RegisterSuccessRoute: RegisterSuccessRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  ConferencesConferenceIdRoute: ConferencesConferenceIdRoute,
  PapersPaperIdRoute: PapersPaperIdRoute,
  ConferencesIndexRoute: ConferencesIndexRoute,
  PapersIndexRoute: PapersIndexRoute,
  ConferencesConferenceIdPapersPaperIdQaRoute:
    ConferencesConferenceIdPapersPaperIdQaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
