-- Conferences
INSERT INTO Conferences (conf_id, conf_name, start_date, end_date, location, is_active) VALUES 
(1, 'Vietnam AI Summit 2024', '2024-12-01', '2024-12-03', 'Ho Chi Minh City', TRUE),
(2, 'Blockchain Global 2025', '2025-06-15', '2025-06-17', 'Da Nang', TRUE),
(3, 'International Conference on Artificial Intelligence (ICAI 2026)', '2026-05-15', '2026-05-18', 'Hanoi, Vietnam', TRUE),
(4, 'Global Web Technologies Summit', '2026-06-10', '2026-06-12', 'San Francisco, USA', TRUE),
(5, 'IEEE International Symposium on Robotics', '2026-07-20', '2026-07-23', 'Tokyo, Japan', TRUE),
(6, 'Vietnam National Science Forum', '2026-08-05', '2026-08-06', 'Da Nang, Vietnam', TRUE),
(7, 'Sustainable Energy & Environment 2026', '2026-09-12', '2026-09-15', 'Berlin, Germany', TRUE),
(8, 'Cybersecurity Breakthrough Conference', '2026-10-01', '2026-10-03', 'Singapore', TRUE),
(9, 'Modern Medical Informatics Workshop', '2026-11-10', '2026-11-11', 'Ho Chi Minh City, Vietnam', TRUE),
(10, 'Blockchain & Fintech Global Expo', '2026-12-01', '2026-12-04', 'Dubai, UAE', TRUE),
(11, 'Future of Education & EdTech 2027', '2027-01-15', '2027-01-17', 'London, UK', TRUE),
(12, 'Internal R&D Symposium (Archive)', '2025-12-10', '2025-12-11', 'Online', FALSE),
(13, 'Asia-Pacific Medical Informatics Summit', '2026-03-10', '2026-03-12', 'Singapore', TRUE),
(14, 'International Congress on Renewable Energy & Smart Grids', '2026-04-20', '2026-04-22', 'Seoul, South Korea', TRUE),
(15, 'Global Symposium on Digital Law & Intellectual Property', '2026-05-05', '2026-05-07', 'Paris, France', TRUE),
(16, 'Workshop on Edge Computing & IoT Innovations', '2026-06-15', '2026-06-16', 'Bangkok, Thailand', TRUE),
(17, 'Future of FinTech & Decentralized Finance (DeFi)', '2026-07-01', '2026-07-03', 'New York, USA', TRUE),
(18, 'International Conference on Bioinformatics & Genomics', '2026-08-12', '2026-08-14', 'Sydney, Australia', TRUE),
(19, 'Vietnam AI & Data Science Open Forum', '2026-09-20', '2026-09-21', 'Can Tho, Vietnam', TRUE);

-- Roles
INSERT INTO Roles (role_id, role_name) VALUES 
(1, 'ADMIN'), (2, 'SECRETARIAT'), (3, 'AUTHOR'), (4, 'REVIEWER'), (5, 'ATTENDEE');

-- Users (Mật khẩu cho tất cả tài khoản là: 123)
INSERT INTO Users (user_id, full_name, email, is_verified, password_hash, organization, created_at) VALUES 
(1, 'Nguyen Admin', 'admin@conf.com', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'BTC', '2026-01-07 03:47:42.807835'),
(2, 'Le Author', 'alice@uni.edu.vn', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'Hanoi University', '2026-01-07 03:47:42.807835'),
(3, 'Tran Reviewer', 'bob@tech.com', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'FPT Software', '2026-01-07 03:47:42.807835'),
(4, 'Pham Attendee', 'charlie@student.com', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'BK U', '2026-01-07 03:47:42.807835'),
(5, 'James Smith', 'j.smith.admin@globalconf.org', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'MIT', '2026-01-07 04:47:39.214608'),
(6, 'Emily Johnson', 'e.johnson.admin@globalconf.org', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'Stanford University', '2026-01-07 04:47:39.214608'),
(7, 'Michael Williams', 'm.williams.admin@globalconf.org', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'Harvard University', '2026-01-07 04:47:39.214608'),
(8, 'Emma Brown', 'e.brown.admin@globalconf.org', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'Oxford Research', '2026-01-07 04:47:39.214608'),
(9, 'Joshua Jones', 'j.jones.sec@conf-ops.com', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'IEEE Operations', '2026-01-07 04:47:39.214608'),
(10, 'Sophia Garcia', 's.garcia.sec@conf-ops.com', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'ACM Association', '2026-01-07 04:47:39.214608'),
(11, 'Matthew Miller', 'm.miller.sec@conf-ops.com', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'Academic Services', '2026-01-07 04:47:39.214608'),
(12, 'Olivia Davis', 'o.davis.sec@conf-ops.com', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'Event Logistics Inc', '2026-01-07 04:47:39.214608'),
(13, 'Daniel Rodriguez', 'd.rodriguez.author@univ.edu', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'University of Tokyo', '2026-01-07 04:47:39.214608'),
(14, 'Isabella Martinez', 'i.martinez.author@univ.edu', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'NUS Singapore', '2026-01-07 04:47:39.214608'),
(15, 'Christopher Hernandez', 'c.hernandez.author@univ.edu', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'ETH Zurich', '2026-01-07 04:47:39.214608'),
(16, 'Mia Lopez', 'm.lopez.author@univ.edu', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'University of Toronto', '2026-01-07 04:47:39.214608'),
(17, 'Andrew Gonzalez', 'a.gonzalez.rev@peer-review.net', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'DeepMind Research', '2026-01-07 04:47:39.214608'),
(18, 'Charlotte Wilson', 'c.wilson.rev@peer-review.net', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'OpenAI', '2026-01-07 04:47:39.214608'),
(19, 'David Anderson', 'd.anderson.rev@peer-review.net', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'Meta AI Lab', '2026-01-07 04:47:39.214608'),
(20, 'Amelia Thomas', 'a.thomas.rev@peer-review.net', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'Microsoft Research', '2026-01-07 04:47:39.214608'),
(21, 'Joseph Taylor', 'j.taylor.guest@industry.com', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'Google', '2026-01-07 04:47:39.214608'),
(22, 'Abigail Moore', 'a.moore.guest@industry.com', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'Amazon AWS', '2026-01-07 04:47:39.214608'),
(23, 'Samuel Jackson', 's.jackson.guest@industry.com', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'Apple', '2026-01-07 04:47:39.214608'),
(24, 'Elizabeth Martin', 'e.martin.guest@industry.com', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'NVIDIA Corporation', '2026-01-07 04:47:39.214608'),
(25, 'Liam Wilson', 'l.wilson.rev@research.ai', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'Google DeepMind', '2026-01-07 07:14:41.104508'),
(26, 'Noah Miller', 'n.miller.rev@research.ai', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'OpenAI', '2026-01-07 07:14:41.104508'),
(27, 'Oliver Taylor', 'o.taylor.rev@research.ai', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'Meta AI', '2026-01-07 07:14:41.104508'),
(28, 'Sophia Anderson', 's.anderson.rev@research.ai', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'Microsoft Research', '2026-01-07 07:14:41.104508'),
(29, 'Lucas Thomas', 'l.thomas.rev@research.ai', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'Amazon Science', '2026-01-07 07:14:41.104508'),
(30, 'Mia White', 'm.white.rev@research.ai', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'IBM Research', '2026-01-07 07:14:41.104508'),
(31, 'Ethan Harris', 'e.harris.rev@research.ai', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'NVIDIA Research', '2026-01-07 07:14:41.104508'),
(32, 'Ava Martin', 'a.martin.rev@research.ai', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'Intel Labs', '2026-01-07 07:14:41.104508'),
(33, 'Aiden Thompson', 'a.thompson.rev@research.ai', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'Berkeley AI Research', '2026-01-07 07:14:41.104508'),
(34, 'Isabella Young', 'i.young.rev@research.ai', TRUE, '$2b$10$9YoZu.ut0DDmCEiK3FMUKemXAMOwJzRfQvQjH8EohMZ8AAA5c9Bnm', 'Tsinghua University', '2026-01-07 07:14:41.104508');

-- User_Roles
INSERT INTO User_Roles (user_id, role_id) VALUES 
(1, 1),   -- Nguyen Admin (Admin)
(2, 3),   -- Le Author (Author)
(2, 5),   -- Le Author (Attendee - Multi-role)
(3, 3),   -- Tran Reviewer (Author)
(4, 5),   -- Pham Attendee (Attendee)
(5, 1),   -- James Smith (Admin)
(6, 1),   -- Emily Johnson (Admin)
(7, 1),   -- Michael Williams (Admin)
(8, 1),   -- Emma Brown (Admin)
(9, 2),   -- Joshua Jones (Secretariat)
(10, 2),  -- Sophia Garcia (Secretariat)
(11, 2),  -- Matthew Miller (Secretariat)
(12, 2),  -- Olivia Davis (Secretariat)
(13, 3),  -- Daniel Rodriguez (Author)
(14, 3),  -- Isabella Martinez (Author)
(15, 3),  -- Christopher Hernandez (Author)
(16, 3),  -- Mia Lopez (Author)
(17, 3),  -- Andrew Gonzalez (Author)
(18, 3),  -- Charlotte Wilson (Author)
(19, 3),  -- David Anderson (Author)
(20, 3),  -- Amelia Thomas (Author)
(21, 5),  -- Joseph Taylor (Attendee)
(22, 5),  -- Abigail Moore (Attendee)
(23, 5),  -- Samuel Jackson (Attendee)
(24, 5),  -- Elizabeth Martin (Attendee)
(25, 4),  -- Liam Wilson (Reviewer)
(26, 4),  -- Noah Miller (Reviewer)
(27, 4),  -- Oliver Taylor (Reviewer)
(28, 4),  -- Sophia Anderson (Reviewer)
(29, 4),  -- Lucas Thomas (Reviewer)
(30, 4),  -- Mia White (Reviewer)
(31, 4),  -- Ethan Harris (Reviewer)
(32, 4),  -- Ava Martin (Reviewer)
(33, 4),  -- Aiden Thompson (Reviewer)
(34, 4);  -- Isabella Young (Reviewer)

-- Papers
INSERT INTO Papers (paper_id, conference_id, title, abstract, primary_author_id, status, best_paper_candidate, final_decision_date, created_at) VALUES 
(1, 1, 'Optimizing LLMs for Vietnamese Language', NULL, 14, 'ACCEPTED', FALSE, NULL, '2026-01-07 03:47:42.807835'),
(2, 1, 'Secure Smart Contract Design', NULL, 15, 'UNDER_REVIEW', FALSE, NULL, '2026-01-07 03:47:42.807835'),
(3, 1, 'Attention Is All You Need', 'The dominant sequence transduction models are based on complex recurrent or convolutional neural networks in an encoder-decoder configuration. The best performing models also connect the encoder and decoder through an attention mechanism. We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely. Experiments on two machine translation tasks show these models to be superior in quality while being more parallelizable and requiring significantly less time to train. Our model achieves 28.4 BLEU on the WMT 2014 English-to-German translation task, improving over the existing best results, including ensembles by over 2 BLEU. On the WMT 2014 English-to-French translation task, our model establishes a new single-model state-of-the-art BLEU score of 41.8 after training for 3.5 days on eight GPUs, a small fraction of the training costs of the best models from the literature. We show that the Transformer generalizes well to other tasks by applying it successfully to English constituency parsing both with large and limited training data.', 15, 'ACCEPTED', TRUE, NULL, '2026-01-07 04:29:04.768495'),
(4, 1, 'Generative Adversarial Nets', 'We propose a new framework for estimating generative models via an adversarial process, in which we simultaneously train two models: a generative model G that captures the data distribution, and a discriminative model D that estimates the probability that a sample came from the training data rather than G. The training procedure for G is to maximize the probability of D making a mistake. This framework corresponds to a minimax two-player game. In the space of arbitrary functions G and D, a unique solution exists, with G recovering the training data distribution and D equal to 1/2 everywhere. In the case where G and D are defined by multilayer perceptrons, the entire system can be trained with backpropagation. There is no need for any Markov chains or unrolled approximate inference networks during either training or generation of samples. Experiments demonstrate the potential of the framework through qualitative and quantitative evaluation of the generated samples.', 13, 'ACCEPTED', FALSE, NULL, '2026-01-07 04:29:04.768495'),
(5, 2, 'Deep Residual Learning for Image Recognition', 'Deeper neural networks are more difficult to train. We present a residual learning framework to ease the training of networks that are substantially deeper than those used previously. We explicitly reformulate the layers as learning residual functions with reference to the layer inputs, instead of learning unreferenced functions. We provide comprehensive empirical evidence showing that these residual networks are easier to optimize, and can gain accuracy from considerably increased depth. On the ImageNet dataset we evaluate residual nets with a depth of up to 152 layers---8x deeper than VGG nets but still having lower complexity. An ensemble of these residual nets achieves 3.57% error on the ImageNet test set. This result won the 1st place on the ILSVRC 2015 classification task. We also present analysis on CIFAR-10 with 100 and 1000 layers. The depth of representations is of central importance for many visual recognition tasks. Solely due to our extremely deep representations, we obtain a 28% relative improvement on the COCO object detection dataset. Deep residual nets are foundations of our submissions to ILSVRC & COCO 2015 competitions, where we also won the 1st places on the tasks of ImageNet detection, ImageNet localization, COCO detection, and COCO segmentation.', 15, 'SUBMITTED', TRUE, NULL, '2026-01-07 04:29:04.768495'),
(6, 3, 'BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding', 'We introduce a new language representation model called BERT, which stands for Bidirectional Encoder Representations from Transformers. Unlike recent language representation models, BERT is designed to pre-train deep bidirectional representations from unlabeled text by jointly conditioning on both left and right context in all layers. As a result, the pre-trained BERT model can be fine-tuned with just one additional output layer to create state-of-the-art models for a wide range of tasks, such as question answering and language inference, without substantial task-specific architecture modifications. BERT is conceptually simple and empirically powerful. It obtains new state-of-the-art results on eleven natural language processing tasks, including pushing the GLUE score to 80.5% (7.7% point absolute improvement), MultiNLI accuracy to 86.7% (4.6% absolute improvement), SQuAD v1.1 question answering Test F1 to 93.2 (1.5 point absolute improvement) and SQuAD v2.0 Test F1 to 83.1 (5.1 point absolute improvement).', 2, 'UNDER_REVIEW', FALSE, NULL, '2026-01-07 04:29:04.768495'),
(7, 5, 'Adam: A Method for Stochastic Optimization', 'We introduce Adam, an algorithm for first-order gradient-based optimization of stochastic objective functions, based on adaptive estimates of lower-order moments. The method is straightforward to implement, is computationally efficient, has little memory requirements, is invariant to diagonal rescaling of the gradients, and is well suited for problems that are large in terms of data and/or parameters. The method is also appropriate for non-stationary objectives and problems with very noisy and/or sparse gradients. The hyper-parameters have intuitive interpretations and typically require little tuning. Some connections to related algorithms, on which Adam was inspired, are discussed. We also analyze the theoretical convergence properties of the algorithm and provide a regret bound on the convergence rate that is comparable to the best known results under the online convex optimization framework. Empirical results demonstrate that Adam works well in practice and compares favorably to other stochastic optimization methods. Finally, we discuss AdaMax, a variant of Adam based on the infinity norm.', 3, 'ACCEPTED', FALSE, NULL, '2026-01-07 04:29:04.768495'),
(8, 6, 'YOLOv3: An Incremental Improvement', 'We present some updates to YOLO! We made a bunch of little design changes to make it better. We also trained this new network that''s pretty swell. It''s a little bigger than last time but more accurate. It''s still fast though, don''t worry. At 320x320 YOLOv3 runs in 22 ms at 28.2 mAP, as accurate as SSD but three times faster. When we look at the old .5 IOU mAP detection metric YOLOv3 is quite good. It achieves 57.9 mAP@50 in 51 ms on a Titan X, compared to 57.5 mAP@50 in 198 ms by RetinaNet, similar performance but 3.8x faster.', 14, 'REVISION_REQ', FALSE, NULL, '2026-01-07 04:29:04.768495'),
(9, 2, 'Language Models are Few-Shot Learners', 'Recent work has demonstrated substantial gains on many NLP tasks and benchmarks by pre-training on a large corpus of text followed by fine-tuning on a specific task. While typically task-agnostic in architecture, this method still requires task-specific fine-tuning datasets of thousands or tens of thousands of examples. By contrast, humans can generally perform a new language task from only a few examples or from simple instructions - something which current NLP systems still largely struggle to do. Here we show that scaling up language models greatly improves task-agnostic, few-shot performance, sometimes even reaching competitiveness with prior state-of-the-art fine-tuning approaches. Specifically, we train GPT-3, an autoregressive language model with 175 billion parameters, 10x more than any previous non-sparse language model, and test its performance in the few-shot setting. For all tasks, GPT-3 is applied without any gradient updates or fine-tuning, with tasks and few-shot demonstrations specified purely via text interaction with the model. GPT-3 achieves strong performance on many NLP datasets, including translation, question-answering, and cloze tasks, as well as several tasks that require on-the-fly reasoning or domain adaptation, such as unscrambling words, using a novel word in a sentence, or performing 3-digit arithmetic. At the same time, we also identify some datasets where GPT-3''s few-shot learning still struggles, as well as some datasets where GPT-3 faces methodological issues related to training on large web corpora. Finally, we find that GPT-3 can generate samples of news articles which human evaluators have difficulty distinguishing from articles written by humans. We discuss broader societal impacts of this finding and of GPT-3 in general.', 13, 'SUBMITTED', TRUE, NULL, '2026-01-07 04:29:04.768495'),
(10, 8, 'Mastering the game of Go with deep neural networks and tree search', 'The game of Go has long been viewed as the most challenging of classic games for artificial intelligence.', 15, 'ACCEPTED', TRUE, NULL, '2026-01-07 04:29:04.768495'),
(11, 3, 'XGBoost: A Scalable Tree Boosting System', 'Tree boosting is a highly effective and widely used machine learning method. In this paper, we describe a scalable end-to-end tree boosting system called XGBoost, which is used widely by data scientists to achieve state-of-the-art results on many machine learning challenges. We propose a novel sparsity-aware algorithm for sparse data and weighted quantile sketch for approximate tree learning. More importantly, we provide insights on cache access patterns, data compression and sharding to build a scalable tree boosting system. By combining these insights, XGBoost scales beyond billions of examples using far fewer resources than existing systems.', 14, 'UNDER_REVIEW', FALSE, NULL, '2026-01-07 04:29:04.768495'),
(12, 1, 'EfficientNet: Rethinking Model Scaling for Convolutional Neural Networks', 'Convolutional Neural Networks (ConvNets) are commonly developed at a fixed resource budget, and then scaled up for better accuracy if more resources are available. In this paper, we systematically study model scaling and identify that carefully balancing network depth, width, and resolution can lead to better performance. Based on this observation, we propose a new scaling method that uniformly scales all dimensions of depth/width/resolution using a simple yet highly effective compound coefficient. We demonstrate the effectiveness of this method on scaling up MobileNets and ResNet. To go even further, we use neural architecture search to design a new baseline network and scale it up to obtain a family of models, called EfficientNets, which achieve much better accuracy and efficiency than previous ConvNets. In particular, our EfficientNet-B7 achieves state-of-the-art 84.3% top-1 accuracy on ImageNet, while being 8.4x smaller and 6.1x faster on inference than the best existing ConvNet. Our EfficientNets also transfer well and achieve state-of-the-art accuracy on CIFAR-100 (91.7%), Flowers (98.8%), and 3 other transfer learning datasets, with an order of magnitude fewer parameters.', 14, 'REJECTED', FALSE, NULL, '2026-01-07 04:29:04.768495'),
(13, 1, 'Scalable Vision Transformers with Hierarchical Attention', 'The recently proposed Visual image Transformers (ViT) with pure attention have achieved promising performance on image recognition tasks, such as image classification. However, the routine of the current ViT model is to maintain a full-length patch sequence during inference, which is redundant and lacks hierarchical representation. To this end, we propose a Hierarchical Visual Transformer (HVT) which progressively pools visual tokens to shrink the sequence length and hence reduces the computational cost, analogous to the feature maps downsampling in Convolutional Neural Networks (CNNs). It brings a great benefit that we can increase the model capacity by scaling dimensions of depth/width/resolution/patch size without introducing extra computational complexity due to the reduced sequence length. Moreover, we empirically find that the average pooled visual tokens contain more discriminative information than the single class token. To demonstrate the improved scalability of our HVT, we conduct extensive experiments on the image classification task. With comparable FLOPs, our HVT outperforms the competitive baselines on ImageNet and CIFAR-100 datasets', 3, 'ACCEPTED', TRUE, NULL, '2026-01-07 06:10:50.633871'),
(14, 1, 'Denoising Diffusion Probabilistic Models for Image Synthesis', 'We present high quality image synthesis results using diffusion probabilistic models, a class of latent variable models inspired by considerations from nonequilibrium thermodynamics. Our best results are obtained by training on a weighted variational bound designed according to a novel connection between diffusion probabilistic models and denoising score matching with Langevin dynamics, and our models naturally admit a progressive lossy decompression scheme that can be interpreted as a generalization of autoregressive decoding. On the unconditional CIFAR10 dataset, we obtain an Inception score of 9.46 and a state-of-the-art FID score of 3.17. On 256x256 LSUN, we obtain sample quality similar to ProgressiveGAN. Our implementation is available at', 13, 'ACCEPTED', FALSE, NULL, '2026-01-07 06:10:50.633871'),
(15, 2, 'A Survey on the Applications of Zero-Knowledge Proofs', 'Zero-knowledge proofs (ZKPs) represent a revolutionary advance in computational integrity and privacy technology, enabling the secure and private exchange of information without revealing underlying private data. ZKPs have unique advantages in terms of universality and minimal security assumptions when compared to other privacy-sensitive computational methods for distributed systems, such as homomorphic encryption and secure multiparty computation. Their application spans multiple domains, from enhancing privacy in blockchain to facilitating confidential verification of computational tasks. This survey starts with a high-level overview of the technical workings of ZKPs with a focus on an increasingly relevant subset of ZKPs called zk-SNARKS. While there have been prior surveys on the algorithmic and theoretical aspects of ZKPs, our work is distinguished by providing a broader view of practical aspects and describing many recently-developed use cases of ZKPs across various domains. These application domains span blockchain privacy, scaling, storage, and interoperability, as well as non-blockchain applications like voting, authentication, timelocks, and machine learning. Aimed at both practitioners and researchers, the survey also covers foundational components and infrastructure such as zero-knowledge virtual machines (zkVM), domain-specific languages (DSLs), supporting libraries, frameworks, and protocols. We conclude with a discussion on future directions, positioning ZKPs as pivotal in the advancement of cryptographic practices and digital privacy across many applications.', 17, 'UNDER_REVIEW', FALSE, NULL, '2026-01-07 06:10:50.633871'),
(16, 2, 'Web 3.0: The Future of Internet', 'With the rapid growth of the Internet, human daily life has become deeply bound to the Internet. To take advantage of massive amounts of data and information on the internet, the Web architecture is continuously being reinvented and upgraded. From the static informative characteristics of Web 1.0 to the dynamic interactive features of Web 2.0, scholars and engineers have worked hard to make the internet world more open, inclusive, and equal. Indeed, the next generation of Web evolution (i.e., Web 3.0) is already coming and shaping our lives. Web 3.0 is a decentralized Web architecture that is more intelligent and safer than before. The risks and ruin posed by monopolists or criminals will be greatly reduced by a complete reconstruction of the Internet and IT infrastructure. In a word, Web 3.0 is capable of addressing web data ownership according to distributed technology. It will optimize the internet world from the perspectives of economy, culture, and technology. Then it promotes novel content production methods, organizational structures, and economic forms. However, Web 3.0 is not mature and is now being disputed. Herein, this paper presents a comprehensive survey of Web 3.0, with a focus on current technologies, challenges, opportunities, and outlook. This article first introduces a brief overview of the history of World Wide Web as well as several differences among Web 1.0, Web 2.0, Web 3.0, and Web3. Then, some technical implementations of Web 3.0 are illustrated in detail. We discuss the revolution and benefits that Web 3.0 brings. Finally, we explore several challenges and issues in this promising area.', 20, 'SUBMITTED', FALSE, NULL, '2026-01-07 06:10:50.633871'),
(17, 3, 'Autonomous UAV Navigation Using Reinforcement Learning', 'Unmanned aerial vehicles (UAV) are commonly used for missions in unknown environments, where an exact mathematical model of the environment may not be available. This paper provides a framework for using reinforcement learning to allow the UAV to navigate successfully in such environments. We conducted our simulation and real implementation to show how the UAVs can successfully learn to navigate through an unknown environment. Technical aspects regarding to applying reinforcement learning algorithm to a UAV system and UAV flight control were also addressed. This will enable continuing research using a UAV with learning capabilities in more important applications, such as wildfire monitoring, or search and rescue missions.', 18, 'ACCEPTED', TRUE, NULL, '2026-01-07 06:10:50.633871'),
(18, 3, 'Bioinspired Soft Robotics: state of the art, challenges, and future directions', 'Purpose of Review: This review provides an overview of the state of the art in bioinspired soft robotics with by examining advancements in actuation, functionality, modeling, and control. Recent Findings: Recent research into actuation methods, such as artificial muscles, have expanded the functionality and potential use of bioinspired soft robots. Additionally, the application of finite dimensional models has improved computational efficiency for modeling soft continuum systems, and garnered interest as a basis for controller formulation. Summary: Bioinspiration in the field of soft robotics has led to diverse approaches to problems in a range of task spaces. In particular, new capabilities in system simplification, miniaturization, and untethering have each contributed to the field’s growth. There is still significant room for improvement in the streamlining of design and manufacturing for these systems, as well as in their control.', 20, 'REVISION_REQ', FALSE, NULL, '2026-01-07 06:10:50.633871'),
(19, 4, 'Gemini: A Family of Highly Capable Multimodal Models', 'This report introduces a new family of multimodal models, Gemini, that exhibit remarkable capabilities across image, audio, video, and text understanding. The Gemini family consists of Ultra, Pro, and Nano sizes, suitable for applications ranging from complex reasoning tasks to on-device memory-constrained use-cases. Evaluation on a broad range of benchmarks shows that our most-capable Gemini Ultra model advances the state of the art in 30 of 32 of these benchmarks - notably being the first model to achieve human-expert performance on the well-studied exam benchmark MMLU, and improving the state of the art in every one of the 20 multimodal benchmarks we examined. We believe that the new capabilities of the Gemini family in cross-modal reasoning and language understanding will enable a wide variety of use cases. We discuss our approach toward post-training and deploying Gemini models responsibly to users through services including Gemini, Gemini Advanced, Google AI Studio, and Cloud Vertex AI.', 15, 'ACCEPTED', FALSE, NULL, '2026-01-07 06:10:50.633871'),
(20, 5, 'The current scope and stand of carbon capture storage and utilization', 'Over here in this paper, we have tried to present detailed information to the best of our knowledge regarding carbon capture storage and its utilization. CCU as well as CCS may be imagined with corresponding parts inside a coordinated framework that could move towards zero discharges that may be required for environment adjustment in the near times. Carbon Capture Storage may be considered as the wide-range extraction of CO2 from various important resources, it is then allowed and made ready for long-term isolation from the atmosphere and, then followed by its appropriate use. Our objective for this paper was to incorporate many technologies in these fields from the research and developmental activities which were a part of many articles and papers till date to the commercial uses and the challenges which are faced in this field and future scopes in this area. The sole purpose of the paper is to present the information in this domain available via different sources in one single paper which would help researchers a lot during their future references or research. Still, there are many kinds of research going on in this field that could be enhanced and paced up by such informative papers where all the required information is stored in a single paper. For the past twenty years, the oil industry and several scientific institutions have given importance to the concept of carbon capture and storage (CCS). A feasible method for storing carbon must be economical, environmentally friendly, and sustainable over the long term. As a result, carbon capture, utilization, and storage (CCUS) has emerged from CCS. The development of CCUS technology goes beyond the narrow focus on storage as it expanded to use carbon dioxide in oil extraction, treat alkaline industrial waste, and conversion of CO2 into useful chemicals to make this greenhouse gas economically viable. Fossil fuels will continue to be a significant source of energy in the following decades despite worldwide commitments to limit CO2 emissions. By converting high-emission industries to low-emission ones, CCUS contributes to the development of the low-emission economy of the future. Therefore, to improve our understanding of the long-term implications of developing alternative options such as large-scale CO2 injection into geological formations, carbon mineralization, and conversion of CO2 to synthesis, state-of-the-art research on carbon storage and utilization is required, and further analysis to understand the risks of CCUS from a technical, legislative, and political perspective. For individuals up for the challenge, CCUS research offers a chance to tackle technological issues that result in innovations with substantial economic and political implications for the oil and petrol sector.', 15, 'UNDER_REVIEW', FALSE, NULL, '2026-01-07 06:10:50.633871'),
(21, 6, 'Zero-Trust Architecture for Remote Work Security', 'secures remote work by abandoning the "trust but verify" model for "never trust, always verify," meaning every user, device, and connection is continuously authenticated and authorized, regardless of location. Key components include strict identity verification (MFA), least-privilege access, device health checks, micro-segmentation, and continuous monitoring to protect data in decentralized environments, replacing outdated VPN/perimeter security. ZTA is ideal for remote work as it reduces the attack surface and prevents lateral movement, securing access from anywhere, anytime.', 3, 'ACCEPTED', FALSE, NULL, '2026-01-07 06:10:50.633871'),
(22, 6, 'A Multimodal Framework for DeepFake Detection', 'The rapid advancement of deepfake technology poses a significant threat to digital media integrity. Deepfakes, synthetic media created using AI, can convincingly alter videos and audio to misrepresent reality. This creates risks of misinformation, fraud, and severe implications for personal privacy and security. Our research addresses the critical issue of deepfakes through an innovative multimodal approach, targeting both visual and auditory elements. This comprehensive strategy recognizes that human perception integrates multiple sensory inputs, particularly visual and auditory information, to form a complete understanding of media content. For visual analysis, a model that employs advanced feature extraction techniques was developed, extracting nine distinct facial characteristics and then applying various machine learning and deep learning models. For auditory analysis, our model leverages mel-spectrogram analysis for feature extraction and then applies various machine learning and deep learning models. To achieve a combined analysis, real and deepfake audio in the original dataset were swapped for testing purposes and ensured balanced samples. Using our proposed models for video and audio classification i.e. Artificial Neural Network and VGG19, the overall sample is classified as deepfake if either component is identified as such. Our multimodal framework combines visual and auditory analyses, yielding an accuracy of 94%.', 20, 'SUBMITTED', TRUE, NULL, '2026-01-07 06:10:50.633871'),
(23, 7, 'Machine Learning and AI in Cancer Prognosis, Prediction, and Treatment Selection', 'Cancer is a leading cause of morbidity and mortality worldwide. While progress has been made in the diagnosis, prognosis, and treatment of cancer patients, individualized and data-driven care remains a challenge. Artificial intelligence (AI), which is used to predict and automate many cancers, has emerged as a promising option for improving healthcare accuracy and patient outcomes. AI applications in oncology include risk assessment, early diagnosis, patient prognosis estimation, and treatment selection based on deep knowledge. Machine learning (ML), a subset of AI that enables computers to learn from training data, has been highly effective at predicting various types of cancer, including breast, brain, lung, liver, and prostate cancer. In fact, AI and ML have demonstrated greater accuracy in predicting cancer than clinicians. These technologies also have the potential to improve the diagnosis, prognosis, and quality of life of patients with various illnesses, not just cancer. Therefore, it is important to improve current AI and ML technologies and to develop new programs to benefit patients. This article examines the use of AI and ML algorithms in cancer prediction, including their current applications, limitations, and future prospects.', 14, 'ACCEPTED', TRUE, NULL, '2026-01-07 06:10:50.633871'),
(24, 8, 'SoK: Stablecoin Designs, Risks, and the Stablecoin LEGO', 'Stablecoins have become significant assets in modern finance, with a market capitalization exceeding USD 246 billion (May 2025). Yet, despite their systemic importance, a comprehensive and risk-oriented understanding of crucial aspects like their design trade-offs, security dynamics, and interdependent failure pathways often remains underdeveloped. This SoK confronts this gap through a large-scale analysis of 157 research studies, 95 active stablecoins, and 44 major security incidents. Our analysis establishes four pivotal insights: 1) stability is best understood not an inherent property but an emergent, fragile state reliant on the interplay between market confidence and continuous liquidity; 2) stablecoin designs demonstrate trade-offs in risk specialization instead of mitigation; 3) the widespread integration of yield mechanisms imposes a “dual mandate” that creates a systemic tension between the core mission of stability and the high-risk financial engineering required for competitive returns; and 4) major security incidents act as acute “evolutionary pressures”, forging resilience by stress-testing designs and aggressively redefining the security frontier. We introduce the Stablecoin LEGO framework, a quantitative methodology mapping historical failures to current designs. Its application reveals that a lower assessed risk strongly correlates with integrating lessons from past incidents. We hope this provides a systematic foundation for building, evaluating, and regulating more resilient stablecoins.', 16, 'REJECTED', FALSE, NULL, '2026-01-07 06:10:50.633871'),
(25, 1, 'Human-Level Reasoning: A Comparative Study of LLMs', 'Evaluating reasoning ability in Large Language Models (LLMs) is important for advancing artificial intelligence, as it transcends mere linguistic task performance. It involves understanding whether these models truly understand information, perform inferences, and are able to draw conclusions in a logical and valid way. This study compare logical and abstract reasoning skills of several LLMs - including GPT, Claude, DeepSeek, Gemini, Grok, Llama, Mistral, Perplexity, and Sabiá - using a set of eight custom-designed reasoning questions. The LLM results are benchmarked against human performance on the same tasks, revealing significant differences and indicating areas where LLMs struggle with deduction.', 2, 'ACCEPTED', FALSE, NULL, '2026-01-07 06:10:50.633871'),
(26, 2, 'Edge Computing for Real-time Video Analytics', 'This paper proposes a novel edge computing enabled real-time video analysis system for intelligent visual devices. The proposed system consists of a tracking-assisted object detection module (TAODM) and a region of interesting module (ROIM). TAODM adaptively determines the offloading decision to process each video frame locally with a tracking algorithm or to offload it to the edge server inferred by an object detection model. ROIM determines each offloading frame''s resolution and detection model configuration to ensure that the analysis results can return in time. TAODM and ROIM interact jointly to filter the repetitive spatial-temporal semantic information to maximize the processing rate while ensuring high video analysis accuracy. Unlike most existing works, this paper investigates the real-time video analysis systems where the intelligent visual device connects to the edge server through a wireless network with fluctuating network conditions. We decompose the real-time video analysis problem into the offloading decision and configurations selection sub-problems. To solve these two sub-problems, we introduce a double deep Q network (DDQN) based offloading approach and a contextual multi-armed bandit (CMAB) based adaptive configurations selection approach, respectively. A DDQN-CMAB reinforcement learning (DCRL) training framework is further developed to integrate these two approaches to improve the overall video analyzing performance. Extensive simulations are conducted to evaluate the performance of the proposed solution, and demonstrate its superiority over counterparts.', 13, 'UNDER_REVIEW', FALSE, NULL, '2026-01-07 06:10:50.633871'),
(27, 3, 'Human–Robot Collaborations in Smart Manufacturing Environments', 'The successful implementation of Human–Robot Collaboration (HRC) has become a prominent feature of smart manufacturing environments. Key industrial requirements, such as flexibility, efficiency, collaboration, consistency, and sustainability, present pressing HRC needs in the manufacturing sector. This paper provides a systemic review and an in-depth discussion of the key technologies currently being employed in smart manufacturing with HRC systems. The work presented here focuses on the design of HRC systems, with particular attention given to the various levels of Human–Robot Interaction (HRI) observed in the industry. The paper also examines the key technologies being implemented in smart manufacturing, including Artificial Intelligence (AI), Collaborative Robots (Cobots), Augmented Reality (AR), and Digital Twin (DT), and discusses their applications in HRC systems. The benefits and practical instances of deploying these technologies are showcased, emphasizing the substantial prospects for growth and improvement in sectors such as automotive and food. However, the paper also addresses the limitations of HRC utilization and implementation and provides some insights into how the design of these systems should be approached in future work and research. Overall, this paper provides new insights into the current state of HRC in smart manufacturing and serves as a useful resource for those interested in the ongoing development of HRC systems in the industry.', 17, 'ACCEPTED', FALSE, NULL, '2026-01-07 06:10:50.633871'),
(28, 5, 'Optimizing Energy Distribution in Smart Grids with DRL', 'The rapid integration of renewable energy sources and the growing complexity of modern power systems have driven the need for efficient energy distribution mechanisms in smart grids. Deep Reinforcement Learning (DRL) has emerged as a promising approach to address these challenges by enabling intelligent decision-making and dynamic resource allocation. This paper explores the application of DRL techniques to optimize energy distribution in smart grids, focusing on key challenges such as demand-response management, grid stability, and renewable energy integration. We investigate state-of-the-art DRL algorithms, including Deep Q-Networks (DQN), Proximal Policy Optimization (PPO), and Soft Actor-Critic (SAC), to develop adaptive control strategies that balance supply and demand while minimizing energy losses and operational costs. A simulation-based framework is employed to model smart grid environments, incorporating stochastic energy generation, varying consumption patterns, and real-time pricing mechanisms. The results demonstrate that DRL-based controllers outperform traditional optimization methods by achieving higher efficiency, scalability, and adaptability to dynamic grid conditions. This research highlights the potential of DRL to revolutionize energy management in smart grids, paving the way for more resilient and sustainable power systems. Future work will explore the integration of multi-agent DRL approaches, enhanced security measures, and real-world deployment challenges.', 13, 'SUBMITTED', FALSE, NULL, '2026-01-07 06:10:50.633871'),
(29, 6, 'The Post-Quantum Cryptography Transition', 'The development of quantum computing threatens the security of our currently widely deployed cryptographic algorithms. While signicant progress has been made in developing post-quantum cryptography (PQC) standards to protect against future quantum computing threats, the U.S. government''s estimated $7.1 billion transition cost for non-National Security Systems alone, coupled with an aggressive 2035 deadline, will require sustained funding, research, and international coordination to successfully upgrade existing cryptographic systems.', 13, 'REVISION_REQ', FALSE, NULL, '2026-01-07 06:10:50.633871'),
(30, 7, 'AI in Genomics: Personalized Medicine', 'Personalized medicine entails tailoring medical care to an individual''s unique genomic and molecular characteristics. AI holds significant promise in advancing the field of personalized medicine. The challenge lies in effectively analyzing vast amounts of data to create tailored treatment approaches. The incorporation of AI into personalized treatment will require healthcare infrastructure adjustments. Upon patients'' arrival, their personal data and clinical information (including images, electrophysiology findings, genetic data, blood pressure, medical notes, etc.) are gathered into the AI system with their consent. Subsequently, the AI system utilizes this patient-specific data to offer healthcare recommendations, aiding healthcare professionals in their clinical decision-making. Results and insights from these recommendations, whether accurate or not, are logged and fed back into the AI system to enhance its precision.', 18, 'ACCEPTED', FALSE, NULL, '2026-01-07 06:10:50.633871'),
(31, 8, 'WHEN IP MEETS NFTs: INTELLECTUAL PROPERTY PROTECTION', 'The world has seen enormous disruption by new age technologies in every domain of today''s economy including the arena of art, music and entertainment. Furthermore, the impact of artificial intelligence and blockchain technology particularly the Non Fungible Tokens (NFTs) has overwhelmed scholars about their understanding of laws related to intellectual property. Advances in technology are expanding the scope of intellectual property beyond traditional patents, trademarks, designs, trade secrets, plant breeders'' rights, and more. Various issues related to intellectual property have taken centre stage in the world of NFTs and Blockchains. Intellectual property disputes over virtual goods and NFTs are on the rise, and countries across the world are endeavoring to address the issues related to the protection of virtual goods. This article analyses the nature and scope of protection granted to virtual goods and NFTs in major jurisdictions viz the US and China. Further, the article analyses if the provisions of Indian IP Laws particularly the Trademarks and Designs Acts are sufficient to grant protection to the virtual goods.', 19, 'SUBMITTED', FALSE, NULL, '2026-01-07 06:10:50.633871'),
(32, 4, 'Computer Science Education in the Age of Generative AI', 'Generative AI tools—–most notably large language models (LLMs) like ChatGPT and Codex—–are rapidly revolutionizing computer science education. These tools can generate, debug, and explain code, thereby transforming the landscape of programming instruction. This paper examines the profound opportunities that AI offers for enhancing computer science education in general, from coding assistance to fostering innovative pedagogical practices and streamlining assessments. At the same time, it highlights challenges including academic integrity concerns, the risk of over-reliance on AI, and difficulties in verifying originality. We discuss what computer science educators should teach in the AI era, how to best integrate these technologies into curricula, and the best practices for assessing student learning in an environment where AI can generate code, prototypes and user feedback. Finally, we propose a set of policy recommendations designed to harness the potential of generative AI while preserving the integrity and rigour of computer science education. Empirical data and emerging studies are used throughout to support our arguments.', 16, 'ACCEPTED', FALSE, NULL, '2026-01-07 06:10:50.633871');

--Paper Versions
INSERT INTO Paper_Versions (version_id, paper_id, file_path, version_number, is_final, plagiarism_safe, format_ok, upload_date, upload_by) VALUES 
(1, 1, '/uploads/p1_v1.pdf', 1, FALSE, NULL, NULL, '2026-01-07 03:47:42.807835', 14),
(2, 1, '/uploads/p1_v2_final.pdf', 2, TRUE, TRUE, TRUE, '2026-01-07 03:47:42.807835', 14),
(3, 2, '/uploads/p2_v1.pdf', 1, FALSE, NULL, NULL, '2026-01-07 03:47:42.807835', 15),
(4, 3, '/uploads/papers/paper_3_v1.pdf', 1, FALSE, TRUE, FALSE, '2026-01-07 04:39:02.816025', 15),
(5, 3, 'https://arxiv.org/pdf/1706.03762', 2, TRUE, TRUE, TRUE, '2026-01-07 04:39:02.816025', 15),
(6, 4, 'https://arxiv.org/pdf/1406.2661', 1, FALSE, NULL, TRUE, '2026-01-07 04:39:02.816025', 13),
(7, 5, '/uploads/papers/resnet_v1.pdf', 1, FALSE, FALSE, TRUE, '2026-01-07 04:39:02.816025', 15),
(8, 6, 'https://arxiv.org/pdf/1810.04805', 1, TRUE, TRUE, TRUE, '2026-01-07 04:39:02.816025', 2),
(9, 7, 'https://arxiv.org/pdf/1412.6980', 1, TRUE, TRUE, TRUE, '2026-01-07 04:39:02.816025', 3),
(10, 8, 'https://arxiv.org/pdf/1804.02767', 1, FALSE, TRUE, TRUE, '2026-01-07 04:39:02.816025', 14),
(11, 9, 'https://arxiv.org/pdf/2005.14165', 1, FALSE, TRUE, TRUE, '2026-01-07 04:39:02.816025', 13),
(12, 10, '/uploads/papers/alphago_final.pdf', 1, TRUE, TRUE, TRUE, '2026-01-07 04:39:02.816025', 15),
(13, 11, 'https://arxiv.org/pdf/1603.02754', 1, TRUE, TRUE, TRUE, '2026-01-07 04:39:02.816025', 14),
(14, 12, 'https://arxiv.org/pdf/1905.11946', 1, FALSE, NULL, NULL, '2026-01-07 04:39:02.816025', 14),
(15, 13, 'https://arxiv.org/pdf/2103.10619', 1, TRUE, TRUE, TRUE, '2026-01-07 06:35:23.374028', 3),
(16, 14, 'https://arxiv.org/abs/2006.11239', 1, TRUE, TRUE, TRUE, '2026-01-07 06:35:23.374028', 13),
(17, 15, 'https://arxiv.org/pdf/2408.00243', 1, FALSE, TRUE, TRUE, '2026-01-07 06:35:23.374028', 17),
(18, 16, 'https://arxiv.org/pdf/2304.06032', 1, FALSE, NULL, TRUE, '2026-01-07 06:35:23.374028', 20),
(19, 17, 'https://arxiv.org/pdf/1801.05086', 1, TRUE, TRUE, TRUE, '2026-01-07 06:35:23.374028', 18),
(20, 18, 'https://arxiv.org/pdf/2312.12312', 1, FALSE, TRUE, FALSE, '2026-01-07 06:35:23.374028', 20),
(21, 19, 'https://arxiv.org/pdf/2312.11805', 1, TRUE, TRUE, TRUE, '2026-01-07 06:35:23.374028', 15),
(22, 20, 'sciencedirect.com/science/article/pii/S2666016423000737', 1, FALSE, TRUE, TRUE, '2026-01-07 06:35:23.374028', 15),
(23, 21, '/uploads/papers/zero_trust_v1.pdf', 1, TRUE, TRUE, TRUE, '2026-01-07 06:35:23.374028', 3),
(24, 22, 'https://arxiv.org/pdf/2410.03487', 1, FALSE, NULL, NULL, '2026-01-07 06:35:23.374028', 20),
(25, 23, 'https://dovepress.com/article/download/84707', 1, TRUE, TRUE, TRUE, '2026-01-07 06:35:23.374028', 14),
(26, 24, 'https://arxiv.org/pdf/2506.17622', 1, FALSE, FALSE, TRUE, '2026-01-07 06:35:23.374028', 16),
(27, 25, 'https://arxiv.org/pdf/2510.24435', 1, TRUE, TRUE, TRUE, '2026-01-07 06:35:23.374028', 2),
(28, 26, 'https://arxiv.org/pdf/2402.18927', 1, FALSE, TRUE, TRUE, '2026-01-07 06:35:23.374028', 13),
(29, 27, '/uploads/papers/human_robot_v1.pdf', 1, TRUE, TRUE, TRUE, '2026-01-07 06:35:23.374028', 17),
(30, 28, 'https://arxiv.org/html/2510.17380v1', 1, FALSE, TRUE, TRUE, '2026-01-07 06:35:23.374028', 13),
(31, 29, 'https://arxiv.org/pdf/2503.04806', 1, FALSE, TRUE, FALSE, '2026-01-07 06:35:23.374028', 13),
(32, 30, '/uploads/papers/ai_genomics_v1.pdf', 1, TRUE, TRUE, TRUE, '2026-01-07 06:35:23.374028', 18),
(33, 31, '/uploads/papers/nft_ip_law_v1.pdf', 1, FALSE, TRUE, TRUE, '2026-01-07 06:35:23.374028', 19),
(34, 32, 'https://arxiv.org/pdf/2507.02183', 1, TRUE, TRUE, TRUE, '2026-01-07 06:35:23.374028', 16);

-- AI_Paper_Analysis_Logs
INSERT INTO AI_Paper_Analysis_Logs (log_id, version_id, check_type, result_data, passed) VALUES 
(1, 2, 'PLAGIARISM', '{"similarity": 5.2}', TRUE),
(2, 2, 'FORMAT_CHECK', '{"font_error": 0}', TRUE);

-- Reviews
INSERT INTO Reviews (review_id, paper_id, reviewer_id, status, recommendation, score, comments, review_date) VALUES 
(1, 1, 3, 'COMPLETED', 'ACCEPT', 4.5, 'This paper presents a well-motivated and novel approach to the problem, offering clear theoretical insights and practical relevance. The proposed method is original and advances the current state of the art.', '2026-01-07 03:47:42.807835'),
(2, 2, 3, 'COMPLETED', 'REVISION', 3.0, NULL, '2026-01-07 03:47:42.807835'),
(3, 3, 17, 'COMPLETED', 'REVISION', 2.0, 'Some assumptions made by the authors are not clearly stated or justified. The limitations of the proposed approach should be discussed more explicitly.', '2026-01-07 07:18:39.087464'),
(4, 3, 18, 'COMPLETED', 'REJECT', 1.7, 'The paper does not adequately compare against relevant state-of-the-art methods. Some closely related works are either missing or insufficiently discussed.', '2026-01-07 07:18:39.087464'),
(5, 3, 19, 'COMPLETED', 'WEAK_ACCEPT', 3.7, 'The proposed approach is generally sound, though some design choices are not fully justified. Additional analysis would strengthen the methodological rigor.', '2026-01-07 07:18:39.087464'),
(6, 3, 20, 'COMPLETED', 'REJECT', 1.2, 'The reported results are inconsistent and, in some cases, difficult to interpret. Statistical significance is not reported, which weakens the credibility of the conclusions.', '2026-01-07 07:18:39.087464'),
(7, 3, 25, 'COMPLETED', 'REJECT', 0.1, 'The claims made in the paper are overstated and not fully supported by the presented evidence. The conclusions go beyond what the experimental results can justify.', '2026-01-07 07:18:39.087464'),
(8, 3, 26, 'COMPLETED', 'REJECT', 1.6, 'The paper does not demonstrate sufficient novelty. Most of the ideas and techniques appear to be incremental variations of existing work, without clear differentiation from prior literature.', '2026-01-07 07:18:39.087464'),
(9, 3, 27, 'COMPLETED', 'REVISION', 2.5, 'More implementation details and hyperparameter settings should be provided to ensure the results can be reproduced. This revision is essential for technical transparency.', '2026-01-07 07:18:39.087464'),
(10, 3, 28, 'COMPLETED', 'REJECT', 0.1, 'The experimental section is weak. The evaluation is limited in scope, uses too few baselines, and does not convincingly demonstrate the effectiveness of the proposed method.', '2026-01-07 07:18:39.087464'),
(11, 3, 29, 'COMPLETED', 'WEAK_ACCEPT', 3.7, 'The paper is mostly well-written and easy to follow, although certain sections would benefit from clearer explanations and better organization.', '2026-01-07 07:18:39.087464'),
(12, 3, 30, 'COMPLETED', 'WEAK_ACCEPT', 3.9, 'The paper addresses an interesting problem and offers some novel aspects; however, the contribution is relatively incremental. While not groundbreaking, the ideas are still potentially useful.', '2026-01-07 07:18:39.087464'),
(13, 30, 17, 'COMPLETED', 'ACCEPT', 4.6, 'The paper is well-written, logically structured, and easy to read. Figures and tables are clear and effectively support the main claims of the paper.', '2026-01-07 07:18:39.087464'),
(14, 30, 18, 'COMPLETED', 'WEAK_ACCEPT', 3.8, 'The related work section covers the main references, but a deeper discussion of recent state-of-the-art methods would provide better context.', '2026-01-07 07:18:39.087464'),
(15, 30, 19, 'COMPLETED', 'REJECT', 1.7, 'Important implementation details are missing, making it difficult to reproduce the results. Several components of the method are vaguely described.', '2026-01-07 07:18:39.087464'),
(16, 30, 20, 'COMPLETED', 'REVISION', 2.2, 'Some claims in the paper are too strong given the current level of evidence. A revision is required to align the conclusions with the presented results.', '2026-01-07 07:18:39.087464'),
(17, 30, 25, 'COMPLETED', 'REVISION', 2.5, 'While the proposed method is interesting, important methodological details are missing or insufficiently justified. The authors should revise the paper to strengthen the technical soundness.', '2026-01-07 07:18:39.087464'),
(18, 30, 26, 'COMPLETED', 'REVISION', 2.6, 'The paper addresses a relevant problem; however, several key aspects of the approach require clearer explanation. A revision is necessary to improve the overall clarity and understanding.', '2026-01-07 07:18:39.087464'),
(19, 30, 27, 'COMPLETED', 'REVISION', 2.5, 'The experimental section needs to be expanded. Additional baselines, datasets, and ablation studies are required to properly validate the proposed approach.', '2026-01-07 07:18:39.087464'),
(20, 30, 28, 'COMPLETED', 'ACCEPT', 4.4, 'The methodology is sound and clearly described, making the paper easy to follow and reproduce. The authors provide sufficient details and justify their design choices convincingly.', '2026-01-07 07:18:39.087464'),
(21, 11, 17, 'COMPLETED', 'REJECT', 0.5, 'The paper suffers from poor organization and unclear writing. Several sections are confusing, and grammatical issues further reduce readability.', '2026-01-07 07:18:39.087464'),
(22, 11, 18, 'COMPLETED', 'REJECT', 0.6, 'Important implementation details are missing, making it difficult to reproduce the results. Several components of the method are vaguely described.', '2026-01-07 07:18:39.087464'),
(23, 11, 19, 'COMPLETED', 'REVISION', 2.2, 'The related work section is incomplete and should be revised to include more recent and relevant studies. Clearer positioning of the contribution is needed.', '2026-01-07 07:18:39.087464'),
(24, 11, 20, 'COMPLETED', 'REJECT', 0.3, 'The reported results are inconsistent and, in some cases, difficult to interpret. Statistical significance is not reported, which weakens the credibility of the conclusions.', '2026-01-07 07:18:39.087464'),
(25, 11, 25, 'COMPLETED', 'REJECT', 0.7, 'The proposed methodology is underdeveloped and lacks rigorous theoretical grounding. Several key assumptions are not justified, which raises concerns about the validity of the approach.', '2026-01-07 07:18:39.087464'),
(26, 11, 26, 'COMPLETED', 'REJECT', 1.9, 'The reported results are inconsistent and, in some cases, difficult to interpret. Statistical significance is not reported, which weakens the credibility of the conclusions.', '2026-01-07 07:18:39.087464'),
(27, 11, 27, 'COMPLETED', 'WEAK_ACCEPT', 3.0, 'The paper provides interesting insights. Methodology is somewhat lacking in detail.', '2026-01-07 07:18:39.087464'),
(28, 25, 17, 'COMPLETED', 'REVISION', 2.2, 'The paper addresses a relevant problem; however, several key aspects of the approach require clearer explanation. A revision is necessary to improve the overall clarity and understanding.', '2026-01-07 07:18:39.087464'),
(29, 25, 18, 'COMPLETED', 'REJECT', 0.5, 'The motivation of the paper is unclear, and the problem formulation lacks a compelling justification. It is not evident why this approach is necessary or beneficial compared to existing methods.', '2026-01-07 07:18:39.087464'),
(30, 25, 19, 'COMPLETED', 'REJECT', 0.8, 'The paper does not demonstrate sufficient novelty. Most of the ideas and techniques appear to be incremental variations of existing work, without clear differentiation from prior literature.', '2026-01-07 07:18:39.087464'),
(31, 25, 20, 'COMPLETED', 'REJECT', 0.8, 'The proposed methodology is underdeveloped and lacks rigorous theoretical grounding. Several key assumptions are not justified, which raises concerns about the validity of the approach.', '2026-01-07 07:18:39.087464'),
(32, 25, 25, 'COMPLETED', 'WEAK_ACCEPT', 3.9, 'While the main idea is reasonable, some analyses are missing or underdeveloped, which limits the strength of the conclusions.', '2026-01-07 07:18:39.087464'),
(33, 25, 26, 'COMPLETED', 'REJECT', 1.0, 'The paper does not adequately compare against relevant state-of-the-art methods. Some closely related works are either missing or insufficiently discussed.', '2026-01-07 07:18:39.087464'),
(34, 25, 27, 'COMPLETED', 'REVISION', 2.9, 'While the proposed method is interesting, important methodological details are missing or insufficiently justified. The authors should revise the paper to strengthen the technical soundness.', '2026-01-07 07:18:39.087464'),
(35, 25, 28, 'COMPLETED', 'REVISION', 2.9, 'The results are promising, but their interpretation requires further clarification. The authors should revise the discussion to better explain the observed trends.', '2026-01-07 07:18:39.087464'),
(36, 25, 29, 'COMPLETED', 'ACCEPT', 4.5, 'The experimental evaluation is thorough and well-designed. Results are consistently strong across multiple benchmarks, and the comparisons with baselines are fair and informative.', '2026-01-07 07:18:39.087464'),
(37, 15, 17, 'COMPLETED', 'REVISION', 2.8, 'The experimental section needs to be expanded. Additional baselines, datasets, and ablation studies are required to properly validate the proposed approach.', '2026-01-07 07:18:39.087464'),
(38, 15, 18, 'COMPLETED', 'WEAK_ACCEPT', 3.7, 'The paper provides interesting insights. Methodology is solid and well-presented.', '2026-01-07 07:18:39.087464'),
(39, 15, 19, 'COMPLETED', 'REVISION', 2.7, 'Overall, the paper has potential, but substantial revisions are needed before it can be considered for acceptance.', '2026-01-07 07:18:39.087464'),
(40, 15, 20, 'COMPLETED', 'REJECT', 1.2, 'Overall, the paper has limited potential impact. Due to the lack of novelty, weak evaluation, and unclear presentation, it does not meet the standard for acceptance.', '2026-01-07 07:18:39.087464'),
(41, 15, 25, 'COMPLETED', 'REJECT', 1.5, 'The claims made in the paper are overstated and not fully supported by the presented evidence. The conclusions go beyond what the experimental results can justify.', '2026-01-07 07:18:39.087464'),
(42, 15, 26, 'COMPLETED', 'WEAK_ACCEPT', 3.1, 'The experimental results are promising, but the evaluation is somewhat limited. Including more baselines and datasets would improve the overall credibility of the claims.', '2026-01-07 07:18:39.087464'),
(43, 15, 27, 'COMPLETED', 'REJECT', 1.5, 'The motivation of the paper is unclear, and the problem formulation lacks a compelling justification. It is not evident why this approach is necessary or beneficial compared to existing methods.', '2026-01-07 07:18:39.087464'),
(44, 15, 28, 'COMPLETED', 'REVISION', 2.7, 'The paper would benefit from revisions to improve organization and writing quality. Several sections are difficult to follow and should be restructured.', '2026-01-07 07:18:39.087464');


-- Review_AI_Metrics
INSERT INTO Review_AI_Metrics (metric_id, review_id, ai_depth_score, ai_sentiment) VALUES 
(1, 1, 8.5, '{"positive": 0.8}'),
(2, 2, 6.2, '{"constructive": 0.5}');

-- Sessions
INSERT INTO Sessions (session_id, session_name, start_time, room_location, is_ai_generated) VALUES 
(1, 'NLP Morning Session', '2024-12-02 08:00:00', 'Hall A', FALSE);

-- Session_Papers
INSERT INTO Session_Papers (session_id, paper_id, presentation_order) VALUES 
(1, 1, 1);

-- Ticket_Configs
INSERT INTO Ticket_Configs (ticket_id, conference_id, ticket_name, price, quantity_limit, open_time, close_time) VALUES 
(1, 1, 'Early Bird Author', 1500000, 100, '2024-01-01', '2024-11-01'),
(2, 1, 'Regular Attendee', 2000000, 200, '2024-06-01', '2024-11-20');

-- Registrations
INSERT INTO Registrations (registration_id, user_id, ticket_id, paper_id, registration_status, payment_status, qr_code_token) VALUES 
(1, 2, 1, 1, 'APPROVED', 'PAID', 'QR_ALICE_AUTH'),
(2, 4, 2, NULL, 'PENDING', 'UNPAID', NULL);

-- Transactions
INSERT INTO Transactions (trans_id, registration_id, payment_gateway, gateway_trans_code, amount, status) VALUES 
(1, 1, 'MOMO', 'MOMO_TRANS_9999', 1500000, 'SUCCESS'),
(2, 2, 'VNPAY', 'VNPAY_TRANS_8888', 2000000, 'PAYMENT_ERROR');

-- CMS_Contents
INSERT INTO CMS_Contents (content_id, title, body_content, content_type, is_published, created_by) VALUES 
(1, 'Call for Papers 2024', '<p>Submit your paper now!</p>', 'CFP', TRUE, 1);

-- Email_Logs
INSERT INTO Email_Logs (email_log_id, recipient_email, email_type, status) VALUES 
(1, 'alice@uni.edu.vn', 'PAYMENT_CONFIRM', 'SENT'),
(2, 'charlie@student.com', 'PAYMENT_REMINDER', 'SENT');

-- Check data
-- 1. CORE SYSTEM
SELECT * FROM Conferences;
SELECT * FROM Roles;
SELECT * FROM Users;
SELECT * FROM User_Roles;

-- 2. SCIENTIFIC MODULE
SELECT * FROM Papers;
SELECT * FROM Paper_Versions;
SELECT * FROM AI_Paper_Analysis_Logs;
SELECT * FROM Reviews;
SELECT * FROM Review_AI_Metrics;
SELECT * FROM Sessions;
SELECT * FROM Session_Papers;

-- 3. REGISTRATION & COMMUNICATION
SELECT * FROM Ticket_Configs;
SELECT * FROM Registrations;
SELECT * FROM Transactions;
SELECT * FROM CMS_Contents;
SELECT * FROM Email_Logs;